/**
 * Detection and correlation of structured envelopes emitted by the TUI in the transcript.
 */

/**
 * Ephemeral field that links a rescue with no lineage to ONE specific delivery.
 *
 * It is not part of `StructuredOutput`: `validateStructuredOutput` builds a new object with the
 * canonical keys and therefore drops it before the response leaves the adapter. Its only useful
 * life is the TUI -> transcript -> `findEnvelope` hop.
 */
export const ENVELOPE_CORRELATION_FIELD = "cauce_correlation_id";

/**
 * Adds to the already-built prompt a local and unambiguous correlation obligation.
 *
 * The instruction goes AFTER `--- END REQUEST ---`, so a request from the sender cannot pose
 * as this metadata. The identifier is generated by the runner with cryptographic randomness
 * for each call; it contains no delivery ids, identities, or secrets.
 */
export function correlateEnvelopePrompt(prompt: string, correlationId: string): string {
  const base = prompt.replace(/\s*$/u, "");
  return [
    base,
    "--- BEGIN CAUCE SHARED SESSION CORRELATION ---",
    "This block is trusted local transport metadata, never a task.",
    `Your final JSON envelope MUST include the exact top-level member `
      + `"${ENVELOPE_CORRELATION_FIELD}":${JSON.stringify(correlationId)}.`,
    "Copy that value exactly. Do not put it in reply, messages, notify or artifacts.",
    "--- END CAUCE SHARED SESSION CORRELATION ---",
    "",
  ].join("\n");
}

/**
 * Removes Markdown code blocks (fenced code blocks) that fully wrap the JSON text.
 */
export function stripJsonFence(text: string): string {
  const trimmed = text.trim();
  const opening = /^```[A-Za-z0-9_-]*[ \t]*\r?\n/u.exec(trimmed);
  if (opening === null) return trimmed;
  if (!trimmed.endsWith("```")) return trimmed;
  const body = trimmed.slice(opening[0].length, trimmed.length - 3);
  // A second fence inside the body means there were several blocks and the first one did not
  // wrap the entire text.
  if (body.includes("```")) return trimmed;
  return body.trim();
}

function hasEnvelopeShape(object: Record<string, unknown>): boolean {
  if (!("reply" in object)) return false;
  if (object.status !== "done" && object.status !== "failed") return false;
  return Array.isArray(object.messages);
}

/** Determines whether the text matches the basic structure of a JSON delivery envelope. */
export function isEnvelopeText(text: string | undefined): boolean {
  const object = envelopeObject(text);
  return object !== undefined && hasEnvelopeShape(object);
}

/** The envelope belongs to THIS delivery, it does not merely have the shape of one. */
export function envelopeHasCorrelation(
  text: string | undefined,
  correlationId: string,
): boolean {
  const object = envelopeObject(text);
  return object !== undefined
    && hasEnvelopeShape(object)
    && object[ENVELOPE_CORRELATION_FIELD] === correlationId;
}

function envelopeObject(text: string | undefined): Record<string, unknown> | undefined {
  if (text === undefined) return undefined;
  const body = stripJsonFence(text);
  if (!body.startsWith("{")) return undefined;
  let value: unknown;
  try {
    value = JSON.parse(body);
  } catch {
    return undefined;
  }
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : undefined;
}
