import assert from "node:assert/strict";
import { appendFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import type { CommandRunner } from "../src/sdk/types.js";
import { readDegradations } from "../src/shared-session/degradation-log.js";
import { CONTEXT_MARK } from "../src/shared-session/notice.js";
import { PasteSessionRunner } from "../src/shared-session/paste-runner.js";
import { codexTranscript, rolloutSessionId, type RolloutLine } from "../src/shared-session/rollout.js";
import {
  FakeTmux,
  RecordingFallback,
  TmuxResult,
  adapterFor,
  claudeRunner,
  correlationIdFromPrompt,
  envelopeText,
  execute,
  freshState,
  randomUUID,
} from "./shared-session-fixtures.js";

// ---------------------------------------------------------------------------
// codex: the SAME mechanism, and the envelope comes out of its rollout.
// ---------------------------------------------------------------------------

const immediate = (): Promise<void> => Promise.resolve();

/**
 * A rollout line in the format generated by codex.
 */
function rolloutLine(type: string, payload: Record<string, unknown>): string {
  return JSON.stringify({ timestamp: new Date().toISOString(), type, payload });
}

function codexStarted(turnId: string): string {
  return rolloutLine("event_msg", { type: "task_started", turn_id: turnId });
}

/** The request, as codex records it: a `response_item` of role `user` WITH its `turn_id`. */
function codexUser(text: string, turnId: string): string {
  return rolloutLine("response_item", {
    type: "message",
    role: "user",
    content: [{ type: "input_text", text }],
    internal_chat_message_metadata_passthrough: { turn_id: turnId },
  });
}

/** The turn's close, which brings the outcome AND the final response, both with `turn_id`. */
function codexComplete(turnId: string, text: string): string {
  return rolloutLine("event_msg", {
    type: "task_complete", turn_id: turnId, last_agent_message: text,
  });
}

function codexAborted(turnId: string): string {
  return rolloutLine("event_msg", {
    type: "turn_aborted", turn_id: turnId, reason: "interrupted",
  });
}

async function codexWorkspace(name: string): Promise<{
  state: string;
  codexHome: string;
  rollout: string;
  sessionId: string;
}> {
  const { state, home } = await freshState(name);
  const codexHome = join(home, ".codex");
  const day = join(codexHome, "sessions", "2026", "07", "31");
  await mkdir(day, { recursive: true });
  const sessionId = randomUUID();
  // The name carries the session_id, which is where the observed session comes from without opening the file.
  const rollout = join(day, `rollout-2026-07-31T16-33-07-${sessionId}.jsonl`);
  await appendFile(rollout, `${rolloutLine("session_meta", { session_id: sessionId })}\n`);
  return { state, codexHome, rollout, sessionId };
}

function codexRunner(
  options: { alias: string; codexHome: string; tmux: FakeTmux; fallback: CommandRunner },
): PasteSessionRunner<RolloutLine> {
  options.tmux.sessionName = `cauce-${options.alias}`;
  if (options.tmux.sessionOptions.size === 0) options.tmux.paneStartCommand = "exec codex";
  return new PasteSessionRunner({
    alias: options.alias,
    harness: "codex",
    workspace: "/workspace",
    transcript: codexTranscript(options.codexHome),
    tmux: options.tmux,
    fallback: options.fallback,
    sleep: immediate,
    acquireTimeoutMs: 30,
    turnTimeoutMs: 2_000,
    injectTimeoutMs: 20,
    settleMs: 0,
    pollMs: 1,
    readyTimeoutMs: 30,
  });
}

test("el turno del bus entra por la caja de codex y el sobre sale de su rollout", async () => {
  const { state, codexHome, rollout, sessionId } = await codexWorkspace("codex-sobre");
  const tmux = new FakeTmux();
  // The codex box is drawn with `›`, not with `❯`.
  tmux.paneContent = "› ";
  const fallback = new RecordingFallback("{}");
  const turnId = "019fb910-ddd9-7d80-af14-8cb69357d917";
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted(turnId),
      codexUser(text, turnId),
      codexComplete(turnId, envelopeText("desde codex")),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux, fallback });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  assert.equal(output.reply, "desde codex");
  assert.equal(fallback.calls, 0);
  // The request entered through the input box, between brackets and as a SINGLE entry.
  assert.ok(tmux.used("load-buffer"));
  assert.ok(tmux.calls.some((call) => call[0] === "paste-buffer" && call.includes("-p")));
  assert.equal(tmux.submittedCount, 1);
  // And the observed conversation is the rollout's, which is the one the usual path would resume.
  assert.equal(rolloutSessionId(rollout), sessionId);
});

test("codex ignora un rollout headless ajeno y rescata sólo el sobre con su nonce", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-multifile-headless");
  const headlessSessionId = randomUUID();
  const headless = join(
    codexHome,
    "sessions",
    "2026",
    "07",
    "31",
    `rollout-2026-07-31T16-34-00-${headlessSessionId}.jsonl`,
  );
  await appendFile(
    headless,
    `${rolloutLine("session_meta", { session_id: headlessSessionId })}\n`,
  );
  const tmux = new FakeTmux();
  tmux.paneContent = "› \nEsc to interrupt\n";
  const fallback = new RecordingFallback("{}");
  tmux.onSubmit = async (text) => {
    await appendFile(
      headless,
      `${codexComplete("headless", envelopeText("RESPUESTA HEADLESS"))}\n`,
    );
    await appendFile(
      rollout,
      `${codexComplete(
        "fundido",
        envelopeText("RESPUESTA TUI", correlationIdFromPrompt(text)),
      )}\n`,
    );
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux, fallback });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  assert.ok((output.reply ?? "").includes("RESPUESTA TUI"));
  assert.ok(!(output.reply ?? "").includes("RESPUESTA HEADLESS"));
  assert.equal(fallback.calls, 0);
});

test("codex recorta el salto final al enviar y aun así se reconoce el turno", async () => {
  // When the harness trims the trailing newline when recording the prompt, the runner must still recognize the turn.
  const { state, codexHome, rollout } = await codexWorkspace("codex-recorte");
  const tmux = new FakeTmux();
  tmux.paneContent = "› ";
  const fallback = new RecordingFallback("{}");
  const turnId = "019fb92d-2577-7c12-a243-7152c7e05bce";
  tmux.onSubmit = async (text) => {
    // Exactly what the codex box does: trims the trailing whitespace.
    assert.ok(/\s$/u.test(text), "el prompt de protocolo tiene que llegar con blanco al final");
    await appendFile(rollout, `${[
      codexStarted(turnId),
      codexUser(text.replace(/\s+$/u, ""), turnId),
      codexComplete(turnId, envelopeText("recortado y reconocido")),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux, fallback });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  assert.equal(output.reply, "recortado y reconocido");
  // What matters: it did NOT degrade to the usual path and did NOT consume the budget.
  assert.equal(fallback.calls, 0);
});

test("el turno del dueño no puede cortar la cosecha del turno del bus", async () => {
  // The rollout is SHARED: while the bus's turn runs, the owner can launch theirs from the panel.
  // Without filtering by `turn_id`, their `task_complete` would close the harvest and the bus
  // would take the foreign response.
  const { state, codexHome, rollout } = await codexWorkspace("codex-turno-ajeno");
  const tmux = new FakeTmux();
  const fallback = new RecordingFallback("{}");
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted("turno-del-bus"),
      codexUser(text, "turno-del-bus"),
      codexStarted("turno-del-dueño"),
      codexUser("lo que escribió el dueño", "turno-del-dueño"),
      codexComplete("turno-del-dueño", envelopeText("RESPUESTA AJENA")),
      codexComplete("turno-del-bus", envelopeText("MI RESPUESTA")),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux, fallback });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  assert.equal(output.reply, "MI RESPUESTA");
  assert.equal(fallback.calls, 0);
});

test("codex avisa cuando compacta durante el turno", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-compactacion");
  const tmux = new FakeTmux();
  const fallback = new RecordingFallback("{}");
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted("t1"),
      codexUser(text, "t1"),
      // Real form: the codex compaction notice does NOT bring any field, neither numbers nor id.
      rolloutLine("event_msg", { type: "context_compacted" }),
      codexComplete("t1", envelopeText("respondido tras compactar")),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux, fallback });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  const reply = output.reply ?? "";
  assert.ok(reply.includes("respondido tras compactar"));
  assert.ok(reply.includes(CONTEXT_MARK));
  assert.ok(reply.includes("context_compacted"));
  assert.equal(fallback.calls, 0);
  assert.equal((await readDegradations(state))[0]?.fellBack, false);
});

test("Enter aceptado sin startedTurn queda ambiguo y bloquea un segundo pegado", async () => {
  // Accepting Enter is the commit: that the rollout hasn't yet recorded it does NOT prove it
  // didn't run. The old fallback could run the same request twice and free the same pane.
  const { state: _state, codexHome, rollout } = await codexWorkspace("codex-sin-registro");
  const tmux = new FakeTmux();
  const fallback = new RecordingFallback("{}");
  // The Enter produces nothing: the rollout doesn't grow.
  tmux.onSubmit = undefined;

  const runner = codexRunner({ alias: "socrates", codexHome, tmux, fallback });
  const first = await runner.run({
    command: "codex",
    args: [],
    harness: "codex",
    stdin: "pedido que pudo arrancar",
    timeoutMs: 2_000,
    signal: new AbortController().signal,
  });

  assert.equal(first.timedOut, true);
  assert.equal(first.harnessStarted, undefined);
  assert.match(first.stderr, /paste\+Enter.*cuarentena/u);
  assert.equal(fallback.calls, 0);
  assert.equal(tmux.submittedCount, 1);
  assert.match(tmux.sessionOptions.get("@cauce_quarantined_pane") ?? "", /^\$0:@0:%0:4242$/u);

  tmux.paneContent = "› \nEsc to interrupt\n";
  const second = await runner.run({
    command: "codex",
    args: [],
    harness: "codex",
    stdin: "no reutilizar la generación ambigua",
    timeoutMs: 2_000,
    signal: new AbortController().signal,
  });
  assert.equal(second.cancelled, false);
  assert.equal(fallback.calls, 1, "codex sigue generando: la cuarentena no se levanta sola");
  assert.equal(tmux.submittedCount, 1, "el segundo pedido no entra en el pane ambiguo");

  tmux.paneContent = "› ";
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted("t-sano"),
      codexUser(text, "t-sano"),
      codexComplete("t-sano", envelopeText("codex recuperado")),
    ].join("\n")}\n`);
  };
  const third = await runner.run({
    command: "codex",
    args: [],
    harness: "codex",
    stdin: "la caja de codex volvió a estar libre",
    timeoutMs: 2_000,
    signal: new AbortController().signal,
  });
  assert.equal(fallback.calls, 1, "codex ocioso recupera su pane sin que nadie lo respawnee");
  assert.equal(tmux.submittedCount, 2, "el tercer pedido sí entra por la caja de codex");
  assert.match(third.stdout, /codex recuperado/u);
  assert.equal(tmux.sessionOptions.has("@cauce_quarantined_pane"), false);
});

test("un turno que el dueño interrumpe no se cobra como respuesta", async () => {
  // Without this the runner waits the full budget for a response that no one will write anymore,
  // and the owner sees a silent agent for the 30 minutes of the ACK deadline.
  const { state, codexHome, rollout } = await codexWorkspace("codex-interrumpido");
  void state;
  const tmux = new FakeTmux();
  const fallback = new RecordingFallback("{}");
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted("t1"),
      codexUser(text, "t1"),
      codexAborted("t1"),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux, fallback });
  const outcome = await runner.run({
    command: "codex",
    args: [],
    harness: "codex",
    stdin: "pedido del bus",
    timeoutMs: 2_000,
    signal: new AbortController().signal,
  });

  assert.equal(outcome.exitCode, 1);
  assert.match(outcome.stderr, /se interrumpió/u);
  // And it does NOT retry via the usual path: the turn did enter the terminal.
  assert.equal(fallback.calls, 0);
});

test("cancelar durante el preflight corta después del await y no ejecuta ningún camino", async () => {
  const { home, workspace } = await freshState("abort-preflight");
  const tmux = new FakeTmux();
  const fallback = new RecordingFallback("{}");
  const controller = new AbortController();
  const originalRun = tmux.run.bind(tmux);
  tmux.run = async (args, stdin, _control): Promise<TmuxResult> => {
    const response = await originalRun(args, stdin);
    if (args[0] === "list-sessions") controller.abort();
    return response;
  };
  const runner = claudeRunner({ alias: "kratos", home, workspace, tmux, fallback });

  const outcome = await runner.run({
    command: "claude",
    args: [],
    harness: "claude",
    stdin: "no ejecutar",
    timeoutMs: 10_000,
    signal: controller.signal,
  });

  assert.equal(outcome.cancelled, true);
  assert.equal(outcome.harnessStarted, false);
  assert.equal(fallback.calls, 0);
  assert.equal(tmux.used("load-buffer"), false);
  assert.equal(tmux.calls.some((call) => call.includes("Enter")), false);
});
