import assert from "node:assert/strict";
import { appendFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { readDegradations } from "../src/shared-session/degradation-log.js";
import { CONTEXT_MARK } from "../src/shared-session/notice.js";
import { PasteSessionRunner } from "../src/shared-session/paste-runner.js";
import { codexTranscript, rolloutSessionId, type RolloutLine } from "../src/shared-session/rollout.js";
import { CODEX_WAKE_PREFIX } from "../src/shared-session/codex-chain.js";
import {
  FakeTmux,
  TmuxResult,
  adapterFor,
  assertExecutionPrevented,
  claudeRunner,
  correlationIdFromPrompt,
  envelopeText,
  execute,
  freshState,
  randomUUID,
} from "./shared-session-fixtures.js";

// ---------------------------------------------------------------------------
// codex: the SAME mechanism, and the envelope comes out of its rollout.
// ---------------------------------------------------------------------------

const immediate = (): Promise<void> => Promise.resolve();

/**
 * A rollout line in the format generated by codex.
 */
function rolloutLine(type: string, payload: Record<string, unknown>): string {
  return JSON.stringify({ timestamp: new Date().toISOString(), type, payload });
}

function codexStarted(turnId: string): string {
  return rolloutLine("event_msg", { type: "task_started", turn_id: turnId });
}

/** The request, as codex records it: a `response_item` of role `user` WITH its `turn_id`. */
function codexUser(text: string, turnId: string): string {
  return rolloutLine("response_item", {
    type: "message",
    role: "user",
    content: [{ type: "input_text", text }],
    internal_chat_message_metadata_passthrough: { turn_id: turnId },
  });
}

/** The turn's close, which brings the outcome AND the final response, both with `turn_id`. */
function codexComplete(turnId: string, text: string): string {
  return rolloutLine("event_msg", {
    type: "task_complete", turn_id: turnId, last_agent_message: text,
  });
}

function codexAborted(turnId: string): string {
  return rolloutLine("event_msg", {
    type: "turn_aborted", turn_id: turnId, reason: "interrupted",
  });
}

async function codexWorkspace(name: string): Promise<{
  state: string;
  codexHome: string;
  rollout: string;
  sessionId: string;
}> {
  const { state, home } = await freshState(name);
  const codexHome = join(home, ".codex");
  const day = join(codexHome, "sessions", "2026", "07", "31");
  await mkdir(day, { recursive: true });
  const sessionId = randomUUID();
  // The name carries the session_id, which is where the observed session comes from without opening the file.
  const rollout = join(day, `rollout-2026-07-31T16-33-07-${sessionId}.jsonl`);
  await appendFile(rollout, `${rolloutLine("session_meta", { session_id: sessionId })}\n`);
  return { state, codexHome, rollout, sessionId };
}

function codexRunner(
  options: { alias: string; codexHome: string; tmux: FakeTmux; sleep?: (ms: number) => Promise<void>; backgroundWaitMs?: number;
    quietTimeoutMs?: number },
): PasteSessionRunner<RolloutLine> {
  options.tmux.sessionName = `cauce-${options.alias}`;
  if (options.tmux.sessionOptions.size === 0) options.tmux.paneStartCommand = "exec codex";
  return new PasteSessionRunner({
    alias: options.alias,
    harness: "codex",
    workspace: "/workspace",
    transcript: codexTranscript(options.codexHome),
    tmux: options.tmux,
    sleep: options.sleep ?? immediate,
    ...(options.backgroundWaitMs === undefined ? {} : { backgroundWaitMs: options.backgroundWaitMs }),
    ...(options.quietTimeoutMs === undefined ? {} : { quietTimeoutMs: options.quietTimeoutMs }),
    acquireTimeoutMs: 30,
    turnTimeoutMs: 2_000,
    injectTimeoutMs: 20,
    settleMs: 0,
    pollMs: 1,
    readyTimeoutMs: 30,
  });
}

test("el turno del bus entra por la caja de codex y el sobre sale de su rollout", async () => {
  const { state, codexHome, rollout, sessionId } = await codexWorkspace("codex-sobre");
  const tmux = new FakeTmux();
  // The codex box is drawn with `›`, not with `❯`.
  tmux.paneContent = "› ";
  const turnId = "019fb910-ddd9-7d80-af14-8cb69357d917";
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted(turnId),
      codexUser(text, turnId),
      codexComplete(turnId, envelopeText("desde codex")),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  assert.equal(output.reply, "desde codex");
  // The request entered through the input box, between brackets and as a SINGLE entry.
  assert.ok(tmux.used("load-buffer"));
  assert.ok(tmux.calls.some((call) => call[0] === "paste-buffer" && call.includes("-p")));
  assert.equal(tmux.submittedCount, 1);
  // And the observed conversation is the rollout's, which is the one the usual path would resume.
  assert.equal(rolloutSessionId(rollout), sessionId);
});

test("codex ignora un rollout headless ajeno y rescata sólo el sobre con su nonce", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-multifile-headless");
  const headlessSessionId = randomUUID();
  const headless = join(
    codexHome,
    "sessions",
    "2026",
    "07",
    "31",
    `rollout-2026-07-31T16-34-00-${headlessSessionId}.jsonl`,
  );
  await appendFile(
    headless,
    `${rolloutLine("session_meta", { session_id: headlessSessionId })}\n`,
  );
  const tmux = new FakeTmux();
  tmux.paneContent = "› \n"; // idle: codex only takes the box between turns (the merge can still race in)
  tmux.onSubmit = async (text) => {
    await appendFile(
      headless,
      `${codexComplete("headless", envelopeText("RESPUESTA HEADLESS"))}\n`,
    );
    await appendFile(
      rollout,
      `${codexComplete(
        "fundido",
        envelopeText("RESPUESTA TUI", correlationIdFromPrompt(text)),
      )}\n`,
    );
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  assert.ok((output.reply ?? "").includes("RESPUESTA TUI"));
  assert.ok(!(output.reply ?? "").includes("RESPUESTA HEADLESS"));
});

test("codex recorta el salto final al enviar y aun así se reconoce el turno", async () => {
  // When the harness trims the trailing newline when recording the prompt, the runner must still recognize the turn.
  const { state, codexHome, rollout } = await codexWorkspace("codex-recorte");
  const tmux = new FakeTmux();
  tmux.paneContent = "› ";
  const turnId = "019fb92d-2577-7c12-a243-7152c7e05bce";
  tmux.onSubmit = async (text) => {
    // Exactly what the codex box does: trims the trailing whitespace.
    assert.ok(/\s$/u.test(text), "el prompt de protocolo tiene que llegar con blanco al final");
    await appendFile(rollout, `${[
      codexStarted(turnId),
      codexUser(text.replace(/\s+$/u, ""), turnId),
      codexComplete(turnId, envelopeText("recortado y reconocido")),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  assert.equal(output.reply, "recortado y reconocido");
  // What matters: it did NOT degrade to the usual path and did NOT consume the budget.
});

test("el turno del dueño no puede cortar la cosecha del turno del bus", async () => {
  // The rollout is SHARED: while the bus's turn runs, the owner can launch theirs from the panel.
  // Without filtering by `turn_id`, their `task_complete` would close the harvest and the bus
  // would take the foreign response.
  const { state, codexHome, rollout } = await codexWorkspace("codex-turno-ajeno");
  const tmux = new FakeTmux();
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted("turno-del-bus"),
      codexUser(text, "turno-del-bus"),
      codexStarted("turno-del-dueño"),
      codexUser("lo que escribió el dueño", "turno-del-dueño"),
      codexComplete("turno-del-dueño", envelopeText("RESPUESTA AJENA")),
      codexComplete("turno-del-bus", envelopeText("MI RESPUESTA")),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  assert.equal(output.reply, "MI RESPUESTA");
});

test("codex avisa cuando compacta durante el turno", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-compactacion");
  const tmux = new FakeTmux();
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted("t1"),
      codexUser(text, "t1"),
      // Real form: the codex compaction notice does NOT bring any field, neither numbers nor id.
      rolloutLine("event_msg", { type: "context_compacted" }),
      codexComplete("t1", envelopeText("respondido tras compactar")),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await execute(adapter);

  const reply = output.reply ?? "";
  assert.ok(reply.includes("respondido tras compactar"));
  assert.ok(reply.includes(CONTEXT_MARK));
  assert.ok(reply.includes("context_compacted"));
  assert.equal((await readDegradations(state))[0]?.fellBack, false);
});

test("Enter aceptado sin startedTurn queda ambiguo y bloquea un segundo pegado", async () => {
  // Accepting Enter is the commit: that the rollout hasn't yet recorded it does NOT prove it
  // didn't run. The old fallback could run the same request twice and free the same pane.
  const { state: _state, codexHome, rollout } = await codexWorkspace("codex-sin-registro");
  const tmux = new FakeTmux();
  // The Enter produces nothing: the rollout doesn't grow.
  tmux.onSubmit = undefined;

  const runner = codexRunner({ alias: "socrates", codexHome, tmux });
  const first = await runner.run({
    command: "codex",
    args: [],
    harness: "codex",
    stdin: "pedido que pudo arrancar",
    timeoutMs: 2_000,
    signal: new AbortController().signal,
  });

  assert.equal(first.timedOut, true);
  assert.equal(first.harnessStarted, undefined);
  assert.match(first.stderr, /paste\+Enter.*cuarentena/u);
  assert.equal(tmux.submittedCount, 1);
  assert.match(tmux.sessionOptions.get("@cauce_quarantined_pane") ?? "", /^\$0:@0:%0:4242$/u);

  tmux.paneContent = "› \nEsc to interrupt\n";
  const second = await runner.run({
    command: "codex",
    args: [],
    harness: "codex",
    stdin: "no reutilizar la generación ambigua",
    timeoutMs: 2_000,
    signal: new AbortController().signal,
  });
  assert.equal(second.cancelled, false);
  assertExecutionPrevented(runner, second, "session_identity_unverified");
  assert.equal(tmux.submittedCount, 1, "el segundo pedido no entra en el pane ambiguo");

  tmux.paneContent = "› ";
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted("t-sano"),
      codexUser(text, "t-sano"),
      codexComplete("t-sano", envelopeText("codex recuperado")),
    ].join("\n")}\n`);
  };
  const third = await runner.run({
    command: "codex",
    args: [],
    harness: "codex",
    stdin: "la caja de codex volvió a estar libre",
    timeoutMs: 2_000,
    signal: new AbortController().signal,
  });
  assert.equal(tmux.submittedCount, 2, "el tercer pedido sí entra por la caja de codex");
  assert.match(third.stdout, /codex recuperado/u);
  assert.equal(tmux.sessionOptions.has("@cauce_quarantined_pane"), false);
});

test("un turno que el dueño interrumpe no se cobra como respuesta", async () => {
  // Without this the runner waits the full budget for a response that no one will write anymore,
  // and the owner sees a silent agent for the 30 minutes of the ACK deadline.
  const { state, codexHome, rollout } = await codexWorkspace("codex-interrumpido");
  void state;
  const tmux = new FakeTmux();
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[
      codexStarted("t1"),
      codexUser(text, "t1"),
      codexAborted("t1"),
    ].join("\n")}\n`);
  };

  const runner = codexRunner({ alias: "socrates", codexHome, tmux });
  const outcome = await runner.run({
    command: "codex",
    args: [],
    harness: "codex",
    stdin: "pedido del bus",
    timeoutMs: 2_000,
    signal: new AbortController().signal,
  });

  assert.equal(outcome.exitCode, 1);
  assert.match(outcome.stderr, /se interrumpió/u);
  // And it does NOT retry via the usual path: the turn did enter the terminal.
});

test("cancelar durante el preflight corta después del await y no ejecuta ningún camino", async () => {
  const { home, workspace } = await freshState("abort-preflight");
  const tmux = new FakeTmux();
  const controller = new AbortController();
  const originalRun = tmux.run.bind(tmux);
  tmux.run = async (args, stdin, _control): Promise<TmuxResult> => {
    const response = await originalRun(args, stdin);
    if (args[0] === "list-sessions") controller.abort();
    return response;
  };
  const runner = claudeRunner({ alias: "kratos", home, workspace, tmux });

  const outcome = await runner.run({
    command: "claude",
    args: [],
    harness: "claude",
    stdin: "no ejecutar",
    timeoutMs: 10_000,
    signal: controller.signal,
  });

  assert.equal(outcome.cancelled, true);
  assert.equal(outcome.harnessStarted, false);
  assert.equal(tmux.used("load-buffer"), false);
  assert.equal(tmux.calls.some((call) => call.includes("Enter")), false);
});

test("codex pensando («Dismiss and keep waiting») se espera y el turno del bus entra cuando se cierra el aviso", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-pensando");
  const tmux = new FakeTmux();
  tmux.paneContent = [
    "  Giving this request a little extra thought",
    "› 1. Dismiss and keep waiting",
    "  2. Learn more",
    "  No action is required. Codex will keep waiting, and this menu will close when the response is ready.",
  ].join("\n");
  setTimeout(() => { tmux.paneContent = "› "; }, 200); // ~7× the 30 ms the box would otherwise get
  const turnId = "019fb910-ddd9-7d80-af14-8cb69357d918";
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[codexStarted(turnId), codexUser(text, turnId),
      codexComplete(turnId, envelopeText("tras pensar"))].join("\n")}\n`);
  };
  const runner = codexRunner({ alias: "socrates", codexHome, tmux,
    sleep: () => new Promise((done) => { setTimeout(done, 5); }) });
  const output = await execute(await adapterFor(runner, state, "socrates", "codex"));
  assert.equal(output.reply, "tras pensar");
  assert.equal(tmux.submittedCount, 1);
});

test("codex no pega sobre un turno en vuelo del dueño: lo espera (socrates 2026-09-30, el canario cerró su turno)", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-turno-del-duenno");
  const tmux = new FakeTmux();
  tmux.paneContent = "◦ Working (1h 19m 21s • esc to interrupt)\n» Ask Codex to do anything\n";
  let submittedWhileWorking = false;
  setTimeout(() => { tmux.paneContent = "› "; }, 200);
  const turnId = "019fb910-ddd9-7d80-af14-8cb69357d919";
  tmux.onSubmit = async (text) => {
    submittedWhileWorking = tmux.paneContent.includes("esc to interrupt");
    await appendFile(rollout, `${[codexStarted(turnId), codexUser(text, turnId),
      codexComplete(turnId, envelopeText("después del dueño"))].join("\n")}\n`);
  };
  const runner = codexRunner({ alias: "socrates", codexHome, tmux,
    sleep: () => new Promise((done) => { setTimeout(done, 5); }) });
  const output = await execute(await adapterFor(runner, state, "socrates", "codex"));
  assert.equal(submittedWhileWorking, false, "pegó dentro del turno del dueño");
  assert.equal(output.reply, "después del dueño");
});

function codexDelegates(target: string): string {
  return rolloutLine("response_item", { type: "function_call", name: "followup_task", call_id: `call_${target}`,
    arguments: JSON.stringify({ target, message: "<cifrado>" }) });
}
function codexWaitAgent(n: number): string {
  return rolloutLine("response_item", { type: "function_call", name: "wait_agent", call_id: `wait_${String(n)}`,
    arguments: JSON.stringify({ timeout_ms: 10_000 }) });
}
function codexSilentClose(turnId: string): string {
  return rolloutLine("event_msg", { type: "task_complete", turn_id: turnId, last_agent_message: null });
}
const tick = (): Promise<void> => new Promise((done) => { setTimeout(done, 5); });

test("codex que delega y cierra mudo: se lo despierta al instante y la entrega recibe la respuesta del turno despertado", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-delega");
  const tmux = new FakeTmux();
  tmux.paneContent = "› ";
  const submitted: string[] = [];
  tmux.onSubmit = async (text) => {
    submitted.push(text);
    if (submitted.length === 1) {
      await appendFile(rollout, `${[codexStarted("t-bus"), codexUser(text, "t-bus"), codexDelegates("worker"),
        codexSilentClose("t-bus")].join("\n")}\n`);
      return;
    }
    await appendFile(rollout, `${[codexStarted("t-wake"), codexUser(text, "t-wake"),
      codexComplete("t-wake", envelopeText("con lo del subagente"))].join("\n")}\n`);
  };
  const runner = codexRunner({ alias: "socrates", codexHome, tmux, sleep: tick });
  const output = await execute(await adapterFor(runner, state, "socrates", "codex"));
  assert.equal(output.reply, "con lo del subagente");
  assert.equal(submitted.length, 2, "no despertó a la raíz");
  assert.ok(submitted[1]?.startsWith(CODEX_WAKE_PREFIX));
});

test("codex sin reloj: el turno despertado que espera a sus subagentes más que backgroundWaitMs no se corta", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-delega-espera");
  const tmux = new FakeTmux();
  tmux.paneContent = "› ";
  let calls = 0;
  tmux.onSubmit = async (text) => {
    calls += 1;
    if (calls === 1) {
      await appendFile(rollout, `${[codexStarted("t-bus"), codexUser(text, "t-bus"), codexDelegates("lento"),
        codexSilentClose("t-bus")].join("\n")}\n`);
      return;
    }
    await appendFile(rollout, `${[codexStarted("t-wake"), codexUser(text, "t-wake")].join("\n")}\n`);
    for (let n = 1; n <= 4; n += 1) { // wait_agent loops for ~8× backgroundWaitMs, writing as it goes
      setTimeout(() => { void appendFile(rollout, `${codexWaitAgent(n)}\n`); }, n * 100);
    }
    setTimeout(() => { void appendFile(rollout, `${codexComplete("t-wake", envelopeText("esperé al lento"))}\n`); }, 450);
  };
  const runner = codexRunner({ alias: "socrates", codexHome, tmux, backgroundWaitMs: 50, sleep: tick });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const output = await adapter.execute({ prompt: "hola", sessionKey: "auth-v2:prueba", timeoutMs: 10_000,
    timeoutKind: "no-progress", signal: new AbortController().signal });
  assert.equal(output.reply, "esperé al lento");
});

test("codex: si la caja no queda libre para despertarlo, la ventana sin progreso cierra con motivo claro y sin cuarentena", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-delega-caja-ocupada");
  const tmux = new FakeTmux();
  tmux.paneContent = "› ";
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[codexStarted("t-bus"), codexUser(text, "t-bus"), codexDelegates("w"),
      codexSilentClose("t-bus")].join("\n")}\n`);
    tmux.paneContent = "› borrador del dueño sin enviar"; // the owner is typing: no wake may be pasted
  };
  const runner = codexRunner({ alias: "socrates", codexHome, tmux, sleep: tick });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  await assert.rejects(adapter.execute({ prompt: "hola", sessionKey: "auth-v2:prueba", timeoutMs: 400,
    timeoutKind: "no-progress", signal: new AbortController().signal }), /no se llegó a despertarlo/u);
  assert.equal(tmux.submittedCount, 1, "pegó encima del borrador del dueño");
  assert.equal(tmux.used("kill-pane"), false, "no se cuarentena ni se mata un panel ocioso");
});

test("codex: un depósito cauce_reply es la respuesta y no hace falta despertar a nadie", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-delega-deposito");
  const tmux = new FakeTmux();
  tmux.paneContent = "› ";
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[codexStarted("t-bus"), codexUser(text, "t-bus"), codexDelegates("lento"),
      codexSilentClose("t-bus")].join("\n")}\n`);
  };
  const runner = codexRunner({ alias: "socrates", codexHome, tmux, quietTimeoutMs: 50, sleep: tick });
  const adapter = await adapterFor(runner, state, "socrates", "codex");
  const deposit = { reply: "depositado", messages: [], notify: [], status: "done" as const, retryable: false, artifacts: [] };
  const output = await adapter.execute({ prompt: "hola", sessionKey: "auth-v2:prueba", timeoutMs: 5_000,
    timeoutKind: "no-progress", signal: new AbortController().signal, emissionOutput: () => deposit });
  assert.equal(output.reply, "depositado");
  assert.equal(tmux.submittedCount, 1, "no hacía falta despertar a nadie");
});

test("codex: si el dueño pasó a otra conversación, no se pega el despertar ahí y la entrega falla con motivo claro", async () => {
  const { state, codexHome, rollout } = await codexWorkspace("codex-delega-otra-conversacion");
  const tmux = new FakeTmux();
  tmux.paneContent = "› ";
  tmux.onSubmit = async (text) => {
    await appendFile(rollout, `${[codexStarted("t-bus"), codexUser(text, "t-bus"), codexDelegates("w"),
      codexSilentClose("t-bus")].join("\n")}\n`);
  };
  const other = join(codexHome, "sessions", "2026", "07", "31", `rollout-2026-07-31T17-00-00-${randomUUID()}.jsonl`);
  const runner = codexRunner({ alias: "socrates", codexHome, tmux, sleep: async () => {
    await appendFile(other, `${rolloutLine("session_meta", { session_id: "otra", source: "cli" })}\n`); // the owner ran /new
    await new Promise((done) => { setTimeout(done, 5); });
  } });
  await assert.rejects(execute(await adapterFor(runner, state, "socrates", "codex")), /la terminal pasó a otra conversación/u);
  assert.equal(tmux.submittedCount, 1, "pegó el despertar en la conversación nueva del dueño");
});
