#!/usr/bin/env python3
"""Capture and enforce the exact external-writer state for release transitions.

The fleet source of truth is ``ops/container-aliases.json`` and the three checked-in,
generated systemd unit sets.  This helper never discovers units with a glob or reads
unit environments.  It asks systemd only about the exact declared unit names, binds
loaded fragments to the generated bytes, and emits a deterministic, secret-free
snapshot suitable for a content-addressed production selector.
"""

from __future__ import annotations

import argparse
import datetime as dt
import fcntl
import hashlib
import json
import os
import pathlib
import pwd
import re
import secrets
import selectors
import shlex
import signal
import stat
import struct
import subprocess
import sys
import time
from typing import Any

from container_alias_lib import ContainerAliasError, load_container_aliases


DIGEST_RE = re.compile(r"^sha256:[a-f0-9]{64}$")
IMAGE_REF_RE = re.compile(
    r"^[a-z0-9]+(?:[._-][a-z0-9]+)*(?::[0-9]+)?"
    r"(?:/[a-z0-9]+(?:[._-][a-z0-9]+)*)+@sha256:[a-f0-9]{64}$"
)
UNIT_RE = re.compile(r"^cauce-v3-(?:alias|container)-[a-z][a-z0-9-]*\.service$")
HOST_RE = re.compile(r"^[a-z][a-z0-9.-]*$")
USER_RE = re.compile(r"^[a-z_][a-z0-9_-]*[$]?$")
FRAGMENT_PATH_RE = re.compile(r"^/[A-Za-z0-9._/-]+$")
ACTIVE_STATES = {"active", "inactive"}
LOADED_STATES = {"loaded", "not-found"}
ENABLED_STATES = {
    "enabled",
    "enabled-runtime",
    "linked",
    "linked-runtime",
    "disabled",
    "static",
    "indirect",
    "masked",
    "masked-runtime",
    "generated",
    "transient",
    "not-found",
    "",
}
SNAPSHOT_KIND = "cauce-v3-release-writer-snapshot"
MARKER_KIND = "cauce-v3-release-state"
MUTATING_ACTIONS = {
    "fence",
    "guarded-exec",
    "marker",
    "publish",
    "restore",
    "rotation-check",
}
COMPOSE_ROLES = {
    "migrator": "migrator",
    "gateway": "core",
    "dispatcher": "core",
    "outbox-metrics": "core",
    "console": "console",
    "relay-worker": "writer",
    "terminal-relay": "writer",
    "telegram-bridge": "writer",
    "shadow-router": "writer",
    "shadow-guard": "writer",
    "otel-collector": "observability",
    "prometheus": "observability",
    "alertmanager": "observability",
    "postgres": "infrastructure",
}
SYSTEM_PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
_ACCOUNT_CACHE: dict[tuple[str, str], tuple[int, pathlib.Path]] = {}


class WriterStateError(ValueError):
    pass


_OFD_LOCK_FORMAT = "hhqqi"


def ofd_lock_payload(lock_type: int) -> bytes:
    if not hasattr(fcntl, "F_OFD_SETLK"):
        fail("open-file-description locks are unavailable")
    return struct.pack(_OFD_LOCK_FORMAT, lock_type, os.SEEK_SET, 0, 1, 0)


def ofd_lock_conflicts(descriptor: int) -> bool:
    if not hasattr(fcntl, "F_OFD_GETLK"):
        fail("open-file-description lock queries are unavailable")
    result = fcntl.fcntl(
        descriptor,
        fcntl.F_OFD_GETLK,
        ofd_lock_payload(fcntl.F_WRLCK),
    )
    lock_type, _whence, _start, _length, _pid = struct.unpack(
        _OFD_LOCK_FORMAT,
        result,
    )
    if lock_type == fcntl.F_UNLCK:
        return False
    if lock_type not in {fcntl.F_RDLCK, fcntl.F_WRLCK}:
        fail("open-file-description lock query returned an invalid state")
    return True


def fail(message: str) -> None:
    raise WriterStateError(message)


def tool_path(variable: str, default: str) -> str:
    override = os.environ.get(variable)
    if override is None:
        return default
    if os.environ.get("CAUCE_WRITER_TEST_MODE") != "1":
        fail("writer-state test executable override is forbidden")
    path = pathlib.Path(override)
    if (
        not path.is_absolute()
        or not path.is_file()
        or path.is_symlink()
        or not os.access(path, os.X_OK)
    ):
        fail("writer-state test executable override is invalid")
    return os.fspath(path)


def sha256_bytes(content: bytes) -> str:
    return f"sha256:{hashlib.sha256(content).hexdigest()}"


def object_value(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        fail(f"{label} must be an object")
    return value


def array_value(value: Any, label: str) -> list[Any]:
    if not isinstance(value, list):
        fail(f"{label} must be an array")
    return value


def read_json_bytes(content: bytes, label: str) -> dict[str, Any]:
    try:
        decoded = content.decode("utf-8")
        value = json.loads(decoded)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise WriterStateError(f"{label} is not canonical JSON") from error
    return object_value(value, label)


def private_file(path: pathlib.Path, *, label: str, mode: int = 0o600) -> bytes:
    if not path.is_absolute():
        fail(f"{label} path must be absolute")
    try:
        before = path.lstat()
    except OSError as error:
        raise WriterStateError(f"{label} is unavailable") from error
    if (
        not stat.S_ISREG(before.st_mode)
        or stat.S_ISLNK(before.st_mode)
        or before.st_nlink != 1
        or stat.S_IMODE(before.st_mode) != mode
        or before.st_uid not in {0, os.geteuid()}
    ):
        fail(f"{label} must be an owned single-link mode-{mode:04o} regular file")
    flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor = os.open(path, flags)
    try:
        opened = os.fstat(descriptor)
        chunks: list[bytes] = []
        while True:
            chunk = os.read(descriptor, 1024 * 1024)
            if not chunk:
                break
            chunks.append(chunk)
        after = os.fstat(descriptor)
    finally:
        os.close(descriptor)

    def signature(item: os.stat_result) -> tuple[int, ...]:
        return (
            item.st_dev,
            item.st_ino,
            item.st_mode,
            item.st_nlink,
            item.st_uid,
            item.st_gid,
            item.st_size,
            item.st_mtime_ns,
            item.st_ctime_ns,
        )

    if signature(before) != signature(opened) or signature(opened) != signature(after):
        fail(f"{label} changed while it was read")
    return b"".join(chunks)


def authenticated_transition_lock() -> int:
    """Retain and authenticate the release lock for every state mutation.

    The descriptor/token pair is minted only by ``pin-production-release.py
    locked-exec``.  Checking the named inode, exact capability bytes and an
    independently opened non-blocking probe prevents a caller from supplying an
    arbitrary readable descriptor or a stale lock file.
    """
    env_raw = os.environ.get("CAUCE_ENV_FILE", "")
    descriptor_raw = os.environ.get("CAUCE_RELEASE_TRANSITION_LOCK_FD", "")
    token = os.environ.get("CAUCE_RELEASE_TRANSITION_LOCK_TOKEN", "")
    if not env_raw or not pathlib.Path(env_raw).is_absolute():
        fail("production env is required to authenticate writer-state mutation")
    if re.fullmatch(r"[0-9]+", descriptor_raw) is None or int(descriptor_raw) < 3:
        fail("writer-state mutation lacks an inherited release lock descriptor")
    if re.fullmatch(r"[a-f0-9]{64}", token) is None:
        fail("writer-state mutation lacks an inherited release lock capability")

    env_path = pathlib.Path(env_raw)
    try:
        env_metadata = env_path.lstat()
    except OSError as error:
        raise WriterStateError(
            "production env is unavailable for writer-state mutation"
        ) from error
    if (
        not stat.S_ISREG(env_metadata.st_mode)
        or stat.S_ISLNK(env_metadata.st_mode)
        or env_metadata.st_nlink != 1
        or stat.S_IMODE(env_metadata.st_mode) != 0o600
        or env_metadata.st_uid not in {0, os.geteuid()}
    ):
        fail("production env is unsafe for writer-state mutation")

    lock_path = env_path.parent / f".{env_path.name}.release-pin.lock"
    try:
        descriptor = os.dup(int(descriptor_raw))
        opened = os.fstat(descriptor)
        named = lock_path.lstat()
    except OSError as error:
        raise WriterStateError(
            "writer-state inherited release lock is unavailable"
        ) from error
    try:
        if (
            (opened.st_dev, opened.st_ino) != (named.st_dev, named.st_ino)
            or not stat.S_ISREG(opened.st_mode)
            or opened.st_nlink != 1
            or stat.S_IMODE(opened.st_mode) != 0o600
            or opened.st_uid not in {0, os.geteuid()}
        ):
            fail("writer-state inherited release lock identity is invalid")
        if os.pread(descriptor, 65, 0) != f"{token}\n".encode("ascii"):
            fail("writer-state inherited release lock capability does not match")

        flags = os.O_RDWR | os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        probe = os.open(lock_path, flags)
        try:
            try:
                fcntl.flock(probe, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError:
                pass
            else:
                fcntl.flock(probe, fcntl.LOCK_UN)
                fail("writer-state inherited release flock was not already exclusive")

            if not ofd_lock_conflicts(probe):
                fail(
                    "writer-state inherited release OFD lock was not already exclusive"
                )

            if ofd_lock_conflicts(descriptor):
                fail(
                    "writer-state inherited release lock is not owned by this transition"
                )

            try:
                fcntl.flock(probe, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError:
                pass
            else:
                fcntl.flock(probe, fcntl.LOCK_UN)
                fail("writer-state inherited release flock ownership was lost")
            if not ofd_lock_conflicts(probe):
                fail("writer-state inherited release OFD ownership was lost")
        finally:
            os.close(probe)
        return descriptor
    except Exception:
        os.close(descriptor)
        raise


def load_snapshot(
    path: pathlib.Path,
    expected_sha256: str,
    ops_root: pathlib.Path | None = None,
) -> dict[str, Any]:
    if DIGEST_RE.fullmatch(expected_sha256) is None:
        fail("writer snapshot SHA-256 is invalid")
    content = private_file(path, label="writer snapshot")
    if sha256_bytes(content) != expected_sha256:
        fail("writer snapshot differs from its selected SHA-256")
    snapshot = read_json_bytes(content, "writer snapshot")
    validate_snapshot(snapshot, ops_root)
    canonical = (
        json.dumps(snapshot, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode()
    if content != canonical:
        fail("writer snapshot bytes are not canonical")
    return snapshot


def manifest_aliases(ops_root: pathlib.Path) -> dict[str, dict[str, str]]:
    source = ops_root / "container-aliases.json"
    document = read_json_bytes(source.read_bytes(), "container alias manifest")
    if set(document) != {
        "schemaVersion",
        "systemPrincipals",
        "historicalAliases",
        "aliases",
    }:
        fail("container alias manifest has unexpected fields")
    if document.get("schemaVersion") != 2:
        fail("container alias manifest schemaVersion is unsupported")
    try:
        aliases = load_container_aliases(ops_root)
    except (ContainerAliasError, json.JSONDecodeError, OSError) as error:
        raise WriterStateError("container alias manifest is invalid") from error
    result: dict[str, dict[str, str]] = {}
    for alias, body in aliases.items():
        tenant = body["tenant"]
        host = body.get("dockerHost", "local")
        systemd_user = body.get("systemdUser")
        if not isinstance(systemd_user, str) or USER_RE.fullmatch(systemd_user) is None:
            fail(f"alias {alias} must declare an exact systemd user")
        result[alias] = {"host": host, "systemdUser": systemd_user, "tenant": tenant}
    return result


def checksum_manifest(directory: pathlib.Path) -> dict[str, str]:
    manifest = directory / "SHA256SUMS"
    entries: dict[str, str] = {}
    for raw in manifest.read_text(encoding="utf-8").splitlines():
        match = re.fullmatch(r"([a-f0-9]{64})  ([A-Za-z0-9._/-]+)", raw)
        if (
            match is None
            or match.group(2).startswith("/")
            or ".." in pathlib.PurePosixPath(match.group(2)).parts
        ):
            fail(f"invalid generated-unit checksum manifest: {manifest}")
        name = match.group(2)
        if name in entries:
            fail(f"duplicate generated-unit checksum entry: {name}")
        entries[name] = match.group(1)
    if not entries:
        fail(f"generated-unit checksum manifest is empty: {manifest}")
    return entries


def generated_units(
    ops_root: pathlib.Path,
    aliases: dict[str, dict[str, str]],
) -> dict[tuple[str, str], str]:
    families = {
        "host-native": (
            "system",
            ops_root / "generated" / "systemd",
            "cauce-v3-alias-{}.service",
        ),
        "container-system": (
            "system",
            ops_root / "generated" / "container-systemd",
            "cauce-v3-container-{}.service",
        ),
        "container-rootless": (
            "user",
            ops_root / "generated" / "container-systemd" / "rootless",
            "cauce-v3-container-{}.service",
        ),
    }
    result: dict[tuple[str, str], str] = {}
    for family, (_scope, directory, template) in families.items():
        checksums = checksum_manifest(directory)
        for alias in aliases:
            name = template.format(alias)
            path = directory / name
            expected = checksums.get(name)
            if expected is None or not path.is_file() or path.is_symlink():
                fail(
                    f"generated unit is absent from its exact checksum manifest: {family}/{name}"
                )
            observed = hashlib.sha256(path.read_bytes()).hexdigest()
            if observed != expected:
                fail(
                    f"generated unit differs from its checksum manifest: {family}/{name}"
                )
            # Preserve the authenticated content identity, never the pathname:
            # systemctl inventory is remote and can take long enough for an
            # otherwise valid source path to be replaced underneath us.
            result[(family, alias)] = f"sha256:{observed}"
    return result


def parse_show(output: str, expected: list[str]) -> dict[str, dict[str, str]]:
    records: dict[str, dict[str, str]] = {}
    for block in re.split(r"\n\s*\n", output.strip()):
        if not block.strip():
            continue
        values: dict[str, str] = {}
        for raw in block.splitlines():
            if "=" not in raw:
                fail("systemd unit inventory returned a malformed property")
            key, value = raw.split("=", 1)
            if key in values:
                fail("systemd unit inventory returned a duplicate property")
            values[key] = value
        unit = values.get("Id", "")
        if unit not in expected or unit in records:
            fail("systemd unit inventory returned an unexpected or duplicate unit")
        records[unit] = values
    if set(records) != set(expected):
        fail("systemd unit inventory omitted a declared unit")
    return records


def ssh_prefix(host: str, systemd_user: str) -> list[str]:
    if HOST_RE.fullmatch(host) is None or USER_RE.fullmatch(systemd_user) is None:
        fail("writer host routing identity is invalid")
    return [
        tool_path("CAUCE_WRITER_TEST_SSH", "/usr/bin/ssh"),
        "-o",
        "BatchMode=yes",
        "-o",
        "ConnectTimeout=10",
        "--",
        f"{systemd_user}@{host}",
    ]


REMOTE_ACCOUNT_QUERY = """\
import json
import pathlib
import pwd
import sys

account = pwd.getpwnam(sys.argv[1])
print(json.dumps({"home": account.pw_dir, "uid": account.pw_uid}, separators=(",", ":")))
"""


def account_identity(host: str, systemd_user: str) -> tuple[int, pathlib.Path]:
    key = (host, systemd_user)
    cached = _ACCOUNT_CACHE.get(key)
    if cached is not None:
        return cached
    if os.environ.get("CAUCE_WRITER_TEST_MODE") == "1":
        test_uid = os.environ.get("CAUCE_WRITER_TEST_ACCOUNT_UID", "")
        test_home = os.environ.get("CAUCE_WRITER_TEST_ACCOUNT_HOME", "")
        if re.fullmatch(r"[0-9]+", test_uid) is None or not test_home:
            fail("writer-state test account identity is incomplete")
        uid = int(test_uid)
        home = pathlib.Path(test_home)
    elif host == "local":
        try:
            account = pwd.getpwnam(systemd_user)
        except KeyError as error:
            raise WriterStateError(
                "declared systemd user does not exist on its local host"
            ) from error
        uid = account.pw_uid
        home = pathlib.Path(account.pw_dir)
    else:
        completed = run_host_command(
            [*ssh_prefix(host, systemd_user), "/usr/bin/python3", "-", systemd_user],
            label=f"systemd account inventory for host {host}",
            input_text=REMOTE_ACCOUNT_QUERY,
        )
        try:
            document = json.loads(completed.stdout)
        except json.JSONDecodeError as error:
            raise WriterStateError(
                "remote systemd account inventory is invalid"
            ) from error
        if not isinstance(document, dict) or set(document) != {"home", "uid"}:
            fail("remote systemd account inventory is invalid")
        uid = document["uid"]
        home = (
            pathlib.Path(document["home"])
            if isinstance(document["home"], str)
            else pathlib.Path()
        )
    if not isinstance(uid, int) or uid < 0:
        fail("declared systemd account UID is invalid")
    pure_home = pathlib.PurePosixPath(os.fspath(home))
    if (
        not home.is_absolute()
        or str(pure_home) != os.fspath(home)
        or ".." in pure_home.parts
    ):
        fail("declared systemd account home is invalid")
    _ACCOUNT_CACHE[key] = (uid, home)
    return uid, home


def clean_user_environment(
    systemd_user: str, uid: int, home: pathlib.Path
) -> list[str]:
    runtime = f"/run/user/{uid}"
    return [
        "/usr/bin/env",
        "-i",
        f"PATH={SYSTEM_PATH}",
        f"HOME={home}",
        f"USER={systemd_user}",
        f"LOGNAME={systemd_user}",
        "LC_ALL=C",
        f"XDG_RUNTIME_DIR={runtime}",
        f"DBUS_SESSION_BUS_ADDRESS=unix:path={runtime}/bus",
    ]


def systemctl_command(
    host: str,
    systemd_user: str,
    scope: str,
    arguments: list[str],
    *,
    mutating: bool = False,
) -> list[str]:
    if scope not in {"system", "user"}:
        fail("writer systemd scope is invalid")
    systemctl = tool_path("CAUCE_WRITER_TEST_SYSTEMCTL", "/usr/bin/systemctl")
    command = [systemctl, *(["--user"] if scope == "user" else []), *arguments]
    if scope == "user":
        uid, home = account_identity(host, systemd_user)
        command = [*clean_user_environment(systemd_user, uid, home), *command]
    if host == "local":
        if scope == "user":
            uid, _home = account_identity(host, systemd_user)
            if os.geteuid() == uid:
                return command
            if os.geteuid() == 0:
                return ["/usr/sbin/runuser", "-u", systemd_user, "--", *command]
            return ["/usr/bin/sudo", "-n", "-u", systemd_user, "--", *command]
        if mutating and os.geteuid() != 0:
            return ["/usr/bin/sudo", "-n", "--", *command]
        return command
    remote = command
    if mutating and scope == "system":
        remote = ["/usr/bin/sudo", "-n", "--", *remote]
    return [*ssh_prefix(host, systemd_user), *remote]


def run_host_command(
    command: list[str],
    *,
    label: str,
    input_text: str | None = None,
) -> subprocess.CompletedProcess[str]:
    try:
        completed = subprocess.run(
            command,
            check=False,
            text=True,
            capture_output=True,
            input=input_text,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise WriterStateError(f"{label} is unavailable") from error
    if completed.returncode != 0:
        fail(f"{label} is unavailable")
    return completed


def systemctl_show(
    host: str,
    systemd_user: str,
    scope: str,
    units: list[str],
) -> dict[str, dict[str, str]]:
    command = systemctl_command(
        host,
        systemd_user,
        scope,
        [
            "show",
            "--no-pager",
            "--property=Id,LoadState,UnitFileState,ActiveState,SubState,MainPID,FragmentPath,DropInPaths,NeedDaemonReload",
            *units,
        ],
    )
    completed = run_host_command(
        command,
        label=f"{scope} systemd manager inventory for host {host}",
    )
    if not completed.stdout.strip():
        fail(
            f"{scope} systemd manager could not inventory the declared writer units on host {host}"
        )
    return parse_show(completed.stdout, units)


REMOTE_GUARD_READY = "CAUCE_WRITER_REMOTE_GUARD_READY"
REMOTE_GUARD_PROGRAM = """\
import fcntl
import os
import pathlib
import stat
import sys

directory = pathlib.Path(sys.argv[1])
expected_uid = int(sys.argv[2])
try:
    directory.mkdir(mode=0o700, parents=False, exist_ok=True)
except FileExistsError:
    pass
metadata = directory.lstat()
if (
    not stat.S_ISDIR(metadata.st_mode)
    or stat.S_ISLNK(metadata.st_mode)
    or metadata.st_uid != expected_uid
    or stat.S_IMODE(metadata.st_mode) != 0o700
):
    raise SystemExit(21)
lock = directory / "release-writer-transition.lock"
flags = os.O_RDWR | os.O_CREAT | os.O_CLOEXEC
if hasattr(os, "O_NOFOLLOW"):
    flags |= os.O_NOFOLLOW
descriptor = os.open(lock, flags, 0o600)
try:
    opened = os.fstat(descriptor)
    named = lock.lstat()
    if (
        not stat.S_ISREG(opened.st_mode)
        or opened.st_nlink != 1
        or opened.st_uid != expected_uid
        or stat.S_IMODE(opened.st_mode) != 0o600
        or (opened.st_dev, opened.st_ino) != (named.st_dev, named.st_ino)
    ):
        raise SystemExit(22)
    try:
        fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        raise SystemExit(23)
    print("CAUCE_WRITER_REMOTE_GUARD_READY", flush=True)
    sys.stdin.buffer.read(1)
finally:
    os.close(descriptor)
"""


def remote_managers(ops_root: pathlib.Path) -> list[tuple[str, str]]:
    return sorted(
        {
            (entry["host"], entry["systemdUser"])
            for entry in manifest_aliases(ops_root).values()
            if entry["host"] != "local"
        }
    )


def manager_set_sha256(managers: list[tuple[str, str]]) -> str:
    content = json.dumps(managers, separators=(",", ":"), ensure_ascii=True).encode(
        "ascii"
    )
    return sha256_bytes(content)


def remote_guard_directory(host: str, systemd_user: str, uid: int) -> pathlib.Path:
    if os.environ.get("CAUCE_WRITER_TEST_MODE") == "1":
        root = pathlib.Path(os.environ.get("CAUCE_WRITER_TEST_GUARD_ROOT", ""))
        if not root.is_absolute() or not root.is_dir() or root.is_symlink():
            fail("writer-state test guard root is invalid")
        return root / f"{host}-{systemd_user}"
    return pathlib.Path(f"/run/user/{uid}/cauce-v3")


def remote_guard_command(host: str, systemd_user: str) -> list[str]:
    uid, _home = account_identity(host, systemd_user)
    directory = remote_guard_directory(host, systemd_user, uid)
    remote = shlex.join(
        [
            "/usr/bin/python3",
            "-c",
            REMOTE_GUARD_PROGRAM,
            os.fspath(directory),
            str(uid),
        ]
    )
    return [*ssh_prefix(host, systemd_user), remote]


def acquire_remote_guard(host: str, systemd_user: str) -> subprocess.Popen[str]:
    command = remote_guard_command(host, systemd_user)
    try:
        process = subprocess.Popen(
            command,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            bufsize=1,
        )
    except OSError as error:
        raise WriterStateError(
            f"remote writer guard for host {host} is unavailable"
        ) from error
    assert process.stdout is not None
    selector = selectors.DefaultSelector()
    try:
        selector.register(process.stdout, selectors.EVENT_READ)
        ready = selector.select(timeout=10)
        line = process.stdout.readline().strip() if ready else ""
    finally:
        selector.close()
    if line != REMOTE_GUARD_READY or process.poll() is not None:
        if process.stdin is not None:
            process.stdin.close()
        try:
            process.wait(timeout=2)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
        fail(
            f"remote writer guard for host {host} could not acquire its transition lock"
        )
    return process


def process_parent(pid: int) -> int:
    try:
        for line in (
            pathlib.Path(f"/proc/{pid}/status").read_text(encoding="ascii").splitlines()
        ):
            if line.startswith("PPid:\t"):
                value = line.removeprefix("PPid:\t")
                if re.fullmatch(r"[0-9]+", value) is None:
                    break
                return int(value)
    except (OSError, UnicodeError):
        pass
    fail("distributed writer remote guard process ancestry is unavailable")


def is_process_ancestor(ancestor: int, descendant: int) -> bool:
    observed: set[int] = set()
    current = descendant
    while current > 1 and current not in observed:
        observed.add(current)
        current = process_parent(current)
        if current == ancestor:
            return True
    return False


def process_arguments(pid: int) -> list[str]:
    try:
        content = pathlib.Path(f"/proc/{pid}/cmdline").read_bytes()
        return [part.decode("utf-8") for part in content.rstrip(b"\0").split(b"\0")]
    except (OSError, UnicodeError) as error:
        raise WriterStateError(
            "distributed writer remote guard command identity is unavailable"
        ) from error


def process_start_time(pid: int) -> int:
    try:
        raw = pathlib.Path(f"/proc/{pid}/stat").read_text(encoding="ascii")
        _prefix, separator, tail = raw.rpartition(")")
        fields = tail.strip().split()
        if (
            separator != ")"
            or len(fields) < 20
            or re.fullmatch(r"[0-9]+", fields[19]) is None
        ):
            raise ValueError
        return int(fields[19])
    except (OSError, UnicodeError, ValueError) as error:
        raise WriterStateError(
            "distributed writer remote guard start identity is unavailable"
        ) from error


def expected_guard_executable() -> pathlib.Path:
    ssh = pathlib.Path(tool_path("CAUCE_WRITER_TEST_SSH", "/usr/bin/ssh"))
    if os.environ.get("CAUCE_WRITER_TEST_MODE") == "1":
        try:
            first = ssh.read_text(encoding="utf-8").splitlines()[0]
        except (OSError, UnicodeError, IndexError) as error:
            raise WriterStateError(
                "writer-state test SSH interpreter is unavailable"
            ) from error
        match = re.fullmatch(r"#!(/[^\s]+)(?:\s+.*)?", first)
        if match is None:
            fail("writer-state test SSH must have an absolute shebang interpreter")
        return pathlib.Path(match.group(1)).resolve(strict=True)
    return ssh.resolve(strict=True)


def authenticated_remote_guard(snapshot: dict[str, Any]) -> None:
    managers = sorted(
        {
            (row["host"], row["systemdUser"])
            for row in snapshot["aliases"]
            if row["host"] != "local"
        }
    )
    if not managers:
        return
    selected_sha = os.environ.get("CAUCE_WRITER_REMOTE_GUARD_MANAGERS_SHA256", "")
    if selected_sha != manager_set_sha256(managers):
        fail("distributed writer mutation remote guard covers a different manager set")
    try:
        guard_rows = json.loads(os.environ.get("CAUCE_WRITER_REMOTE_GUARDS", ""))
    except json.JSONDecodeError as error:
        raise WriterStateError(
            "distributed writer mutation lacks authenticated remote guards"
        ) from error
    if not isinstance(guard_rows, list) or len(guard_rows) != len(managers):
        fail("distributed writer mutation remote guard set is invalid")
    controller_pid: int | None = None
    descriptors: list[int] = []
    observed_managers: list[tuple[str, str]] = []
    for raw, expected_manager in zip(guard_rows, managers, strict=True):
        if not isinstance(raw, dict) or set(raw) != {
            "controllerPid",
            "fd",
            "host",
            "pid",
            "startTime",
            "systemdUser",
        }:
            fail("distributed writer mutation remote guard record is invalid")
        host, systemd_user = expected_manager
        if (raw.get("host"), raw.get("systemdUser")) != expected_manager:
            fail("distributed writer mutation remote guard placement is invalid")
        descriptor = raw.get("fd")
        ssh_pid = raw.get("pid")
        start_time = raw.get("startTime")
        row_controller = raw.get("controllerPid")
        if any(
            type(value) is not int or value < minimum
            for value, minimum in (
                (descriptor, 3),
                (ssh_pid, 2),
                (start_time, 1),
                (row_controller, 2),
            )
        ):
            fail("distributed writer mutation remote guard process identity is invalid")
        assert (
            isinstance(descriptor, int)
            and isinstance(ssh_pid, int)
            and isinstance(start_time, int)
            and isinstance(row_controller, int)
        )
        if controller_pid is None:
            controller_pid = row_controller
        if (
            row_controller != controller_pid
            or process_parent(ssh_pid) != controller_pid
            or not is_process_ancestor(controller_pid, os.getpid())
        ):
            fail(
                "distributed writer mutation remote guard is outside its controller ancestry"
            )
        expected_arguments = remote_guard_command(host, systemd_user)
        actual_arguments = process_arguments(ssh_pid)
        if os.environ.get("CAUCE_WRITER_TEST_MODE") == "1":
            if (
                len(actual_arguments) < len(expected_arguments)
                or actual_arguments[-len(expected_arguments) :] != expected_arguments
            ):
                fail(
                    "distributed writer remote guard command differs from canonical SSH authority"
                )
        elif actual_arguments != expected_arguments:
            fail(
                "distributed writer remote guard command differs from canonical SSH authority"
            )
        try:
            executable = pathlib.Path(os.readlink(f"/proc/{ssh_pid}/exe")).resolve(
                strict=True
            )
        except OSError as error:
            raise WriterStateError(
                "distributed writer remote guard executable identity is unavailable"
            ) from error
        if (
            executable != expected_guard_executable()
            or process_start_time(ssh_pid) != start_time
        ):
            fail(
                "distributed writer remote guard process differs from canonical SSH authority"
            )
        if not hasattr(os, "pidfd_open"):
            fail("distributed writer remote guard requires pidfd support")
        try:
            pid_descriptor = os.pidfd_open(ssh_pid, 0)
        except OSError as error:
            raise WriterStateError(
                "distributed writer remote guard pidfd is unavailable"
            ) from error
        try:
            try:
                metadata = os.fstat(descriptor)
                peer = os.stat(f"/proc/{ssh_pid}/fd/1")
            except OSError as error:
                raise WriterStateError(
                    "distributed writer mutation remote guard is unavailable"
                ) from error
            if not stat.S_ISFIFO(metadata.st_mode) or (
                metadata.st_dev,
                metadata.st_ino,
            ) != (peer.st_dev, peer.st_ino):
                fail(
                    "distributed writer mutation remote guard descriptor has no canonical SSH peer"
                )
            pid_poller = selectors.DefaultSelector()
            try:
                pid_poller.register(pid_descriptor, selectors.EVENT_READ)
                if pid_poller.select(timeout=0):
                    fail(
                        "distributed writer mutation remote guard process already exited"
                    )
            finally:
                pid_poller.close()
        finally:
            os.close(pid_descriptor)
        descriptors.append(descriptor)
        observed_managers.append((host, systemd_user))
    if observed_managers != managers or controller_pid is None:
        fail("distributed writer mutation remote guard set is incomplete")
    poller = selectors.DefaultSelector()
    try:
        for descriptor in descriptors:
            poller.register(descriptor, selectors.EVENT_READ)
        if poller.select(timeout=0):
            fail("distributed writer mutation remote guard session was lost")
    finally:
        poller.close()


def release_remote_guards(guards: list[subprocess.Popen[str]]) -> None:
    for guard in guards:
        if guard.stdin is not None:
            try:
                guard.stdin.close()
            except OSError:
                pass
    for guard in guards:
        try:
            guard.wait(timeout=5)
        except subprocess.TimeoutExpired:
            guard.kill()
            guard.wait()


def guarded_exec(ops_root: pathlib.Path, command: list[str]) -> int:
    if command and command[0] == "--":
        command = command[1:]
    if not command or not pathlib.Path(command[0]).is_absolute():
        fail("distributed writer guarded command must use an absolute executable")
    managers = remote_managers(ops_root)
    guards: list[tuple[str, str, subprocess.Popen[str]]] = []
    child: subprocess.Popen[bytes] | None = None
    try:
        for host, systemd_user in managers:
            guards.append(
                (host, systemd_user, acquire_remote_guard(host, systemd_user))
            )
        guard_fds = [
            guard.stdout.fileno() for _host, _user, guard in guards if guard.stdout
        ]
        environment = os.environ.copy()
        environment["CAUCE_WRITER_REMOTE_GUARD_FD"] = (
            str(guard_fds[0]) if guard_fds else "none"
        )
        environment["CAUCE_WRITER_REMOTE_GUARD_MANAGERS_SHA256"] = manager_set_sha256(
            managers
        )
        environment["CAUCE_WRITER_REMOTE_GUARDS"] = json.dumps(
            [
                {
                    "controllerPid": os.getpid(),
                    "fd": guard.stdout.fileno(),
                    "host": host,
                    "pid": guard.pid,
                    "startTime": process_start_time(guard.pid),
                    "systemdUser": systemd_user,
                }
                for host, systemd_user, guard in guards
                if guard.stdout
            ],
            sort_keys=True,
            separators=(",", ":"),
        )
        transition_fd = int(environment["CAUCE_RELEASE_TRANSITION_LOCK_FD"])
        child = subprocess.Popen(
            command,
            env=environment,
            pass_fds=tuple({transition_fd, *guard_fds}),
            start_new_session=True,
        )
        guard_lost = False
        while child.poll() is None:
            if any(guard.poll() is not None for _host, _user, guard in guards):
                guard_lost = True
                os.killpg(child.pid, signal.SIGTERM)
                try:
                    child.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    os.killpg(child.pid, signal.SIGKILL)
                    child.wait()
                break
            time.sleep(0.1)
        if guard_lost:
            fail("a remote writer guard was lost during the release transition")
        return child.wait()
    finally:
        release_remote_guards([guard for _host, _user, guard in guards])


REMOTE_FRAGMENT_HASH = """\
import hashlib
import os
import pathlib
import stat
import sys

path = pathlib.Path(sys.argv[1])
expected_uid = int(sys.argv[2])
before = path.lstat()
if (
    not stat.S_ISREG(before.st_mode)
    or stat.S_ISLNK(before.st_mode)
    or before.st_nlink != 1
    or before.st_uid != expected_uid
    or stat.S_IMODE(before.st_mode) != 0o644
):
    raise SystemExit(2)
flags = os.O_RDONLY | os.O_CLOEXEC
if hasattr(os, "O_NOFOLLOW"):
    flags |= os.O_NOFOLLOW
descriptor = os.open(path, flags)
try:
    opened = os.fstat(descriptor)
    digest = hashlib.sha256()
    while True:
        chunk = os.read(descriptor, 1024 * 1024)
        if not chunk:
            break
        digest.update(chunk)
    after = os.fstat(descriptor)
finally:
    os.close(descriptor)
named_after = path.lstat()
signature = lambda item: (
    item.st_dev, item.st_ino, item.st_mode, item.st_nlink, item.st_uid,
    item.st_gid, item.st_size, item.st_mtime_ns, item.st_ctime_ns,
)
if (
    signature(before) != signature(opened)
    or signature(opened) != signature(after)
    or signature(after) != signature(named_after)
):
    raise SystemExit(3)
print("sha256:" + digest.hexdigest())
"""


def canonical_fragment_path(
    host: str,
    systemd_user: str,
    scope: str,
    value: str,
    name: str,
) -> tuple[pathlib.Path, int]:
    if FRAGMENT_PATH_RE.fullmatch(value) is None:
        fail("declared writer unit fragment path is invalid")
    path = pathlib.PurePosixPath(value)
    if (
        str(path) != value
        or ".." in path.parts
        or "." in path.parts
        or path.name != name
    ):
        fail("declared writer unit fragment path is not canonical")
    manager_uid, manager_home = account_identity(host, systemd_user)
    if scope == "system":
        expected = pathlib.Path("/etc/systemd/system") / name
        expected_uid = 0
    elif scope == "user":
        expected = manager_home / ".config" / "systemd" / "user" / name
        expected_uid = manager_uid
    else:
        fail("declared writer unit fragment scope is invalid")
    if pathlib.Path(value) != expected:
        fail("declared writer unit fragment is outside its canonical manager path")
    return expected, expected_uid


def local_fragment_sha(path: pathlib.Path, expected_uid: int) -> str:
    try:
        before = path.lstat()
        if (
            not stat.S_ISREG(before.st_mode)
            or stat.S_ISLNK(before.st_mode)
            or before.st_nlink != 1
            or before.st_uid != expected_uid
            or stat.S_IMODE(before.st_mode) != 0o644
        ):
            fail("declared writer unit fragment is unsafe")
        flags = os.O_RDONLY | os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor = os.open(path, flags)
        try:
            opened = os.fstat(descriptor)
            digest = hashlib.sha256()
            while True:
                chunk = os.read(descriptor, 1024 * 1024)
                if not chunk:
                    break
                digest.update(chunk)
            after = os.fstat(descriptor)
        finally:
            os.close(descriptor)
        named_after = path.lstat()
    except OSError as error:
        raise WriterStateError(
            "declared writer unit fragment is unavailable"
        ) from error

    def signature(item: os.stat_result) -> tuple[int, ...]:
        return (
            item.st_dev,
            item.st_ino,
            item.st_mode,
            item.st_nlink,
            item.st_uid,
            item.st_gid,
            item.st_size,
            item.st_mtime_ns,
            item.st_ctime_ns,
        )

    if (
        signature(before) != signature(opened)
        or signature(opened) != signature(after)
        or signature(after) != signature(named_after)
    ):
        fail("declared writer unit fragment changed while it was authenticated")
    return f"sha256:{digest.hexdigest()}"


def installed_fragment_sha(
    host: str,
    systemd_user: str,
    path: pathlib.Path,
    expected_uid: int,
) -> str:
    if host == "local":
        return local_fragment_sha(path, expected_uid)
    completed = run_host_command(
        [
            *ssh_prefix(host, systemd_user),
            "/usr/bin/python3",
            "-",
            os.fspath(path),
            str(expected_uid),
        ],
        label=f"writer unit fragment authentication for host {host}",
        input_text=REMOTE_FRAGMENT_HASH,
    )
    digest = completed.stdout.strip()
    if DIGEST_RE.fullmatch(digest) is None:
        fail(
            f"writer unit fragment authentication for host {host} returned invalid evidence"
        )
    return digest


def accredited_unit(
    *,
    host: str,
    systemd_user: str,
    family: str,
    scope: str,
    name: str,
    values: dict[str, str],
    source_sha256: str,
) -> dict[str, Any]:
    load = values.get("LoadState", "")
    active = values.get("ActiveState", "")
    unit_file = values.get("UnitFileState", "")
    sub = values.get("SubState", "")
    main_pid_raw = values.get("MainPID", "")
    fragment = values.get("FragmentPath", "")
    dropins = values.get("DropInPaths", "")
    reload_needed = values.get("NeedDaemonReload", "")
    if (
        load not in LOADED_STATES
        or active not in ACTIVE_STATES
        or unit_file not in ENABLED_STATES
    ):
        fail(f"declared writer unit is in an unsupported state: {host}/{scope}/{name}")
    if (load == "loaded" and unit_file not in {"enabled", "disabled"}) or (
        load == "not-found"
        and (unit_file not in {"not-found", ""} or active != "inactive")
    ):
        fail(
            f"declared writer unit lacks an exact reversible state: {host}/{scope}/{name}"
        )
    try:
        main_pid = int(main_pid_raw)
    except ValueError as error:
        raise WriterStateError(
            f"declared writer unit has an invalid MainPID: {host}/{scope}/{name}"
        ) from error
    if main_pid < 0 or (active == "active") != (main_pid > 0):
        fail(f"declared writer unit process state is ambiguous: {host}/{scope}/{name}")
    if dropins:
        fail(f"declared writer unit has unaccredited drop-ins: {host}/{scope}/{name}")
    if reload_needed != "no":
        fail(
            f"declared writer unit requires a systemd daemon reload: {host}/{scope}/{name}"
        )
    fragment_sha: str | None = None
    if load == "loaded":
        installed, expected_uid = canonical_fragment_path(
            host,
            systemd_user,
            scope,
            fragment,
            name,
        )
        fragment_sha = installed_fragment_sha(
            host,
            systemd_user,
            installed,
            expected_uid,
        )
        if fragment_sha != source_sha256:
            fail(
                f"installed writer unit differs from generated authority: "
                f"{host}/{scope}/{name}"
            )
        refreshed = systemctl_show(host, systemd_user, scope, [name])[name]
        if refreshed != values:
            fail(
                f"declared writer unit changed during authentication: {host}/{scope}/{name}"
            )
    elif fragment:
        fail(
            f"not-found writer unit unexpectedly has a fragment: {host}/{scope}/{name}"
        )
    return {
        "activeState": active,
        "family": family,
        "fragmentSha256": fragment_sha,
        "loadState": load,
        "mainPid": main_pid,
        "name": name,
        "scope": scope,
        "subState": sub,
        "unitFileState": unit_file,
    }


def unit_inventory(
    ops_root: pathlib.Path,
    aliases: dict[str, dict[str, str]],
    *,
    admit_partial_transition: bool = False,
) -> list[dict[str, Any]]:
    sources = generated_units(ops_root, aliases)
    names = {
        "host-native": {alias: f"cauce-v3-alias-{alias}.service" for alias in aliases},
        "container-system": {
            alias: f"cauce-v3-container-{alias}.service" for alias in aliases
        },
        "container-rootless": {
            alias: f"cauce-v3-container-{alias}.service" for alias in aliases
        },
    }
    managers = sorted(
        {(entry["host"], entry["systemdUser"]) for entry in aliases.values()}
    )
    inventories: dict[tuple[str, str, str], dict[str, dict[str, str]]] = {}
    for host, systemd_user in managers:
        system_names = [
            *names["host-native"].values(),
            *names["container-system"].values(),
        ]
        user_names = list(names["container-rootless"].values())
        inventories[(host, systemd_user, "system")] = systemctl_show(
            host,
            systemd_user,
            "system",
            system_names,
        )
        inventories[(host, systemd_user, "user")] = systemctl_show(
            host,
            systemd_user,
            "user",
            user_names,
        )
    result: list[dict[str, Any]] = []
    for alias in aliases:
        host = aliases[alias]["host"]
        systemd_user = aliases[alias]["systemdUser"]
        alias_units: list[dict[str, Any]] = []
        for family, scope in (
            ("host-native", "system"),
            ("container-system", "system"),
            ("container-rootless", "user"),
        ):
            name = names[family][alias]
            values = inventories[(host, systemd_user, scope)][name]
            alias_units.append(
                accredited_unit(
                    host=host,
                    systemd_user=systemd_user,
                    family=family,
                    scope=scope,
                    name=name,
                    values=values,
                    source_sha256=sources[(family, alias)],
                )
            )
        active_units = [item for item in alias_units if item["activeState"] == "active"]
        enabled_units = [
            item
            for item in alias_units
            if item["unitFileState"]
            in {"enabled", "enabled-runtime", "linked", "linked-runtime"}
        ]
        if len(active_units) > 1 or len(enabled_units) > 1:
            fail(f"alias {alias} has overlapping writer unit families")
        if (
            not admit_partial_transition
            and active_units
            and (not enabled_units or active_units[0] is not enabled_units[0])
        ):
            fail(
                f"alias {alias} active writer unit is not exactly and reversibly enabled"
            )
        result.append(
            {
                "alias": alias,
                "host": host,
                "systemdUser": systemd_user,
                "tenant": aliases[alias]["tenant"],
                "units": alias_units,
            }
        )
    for alias, placement in aliases.items():
        for host, systemd_user in managers:
            for family, scope in (
                ("host-native", "system"),
                ("container-system", "system"),
                ("container-rootless", "user"),
            ):
                if scope == "system":
                    canonical_manager = host == placement["host"]
                else:
                    canonical_manager = (
                        host == placement["host"]
                        and systemd_user == placement["systemdUser"]
                    )
                if canonical_manager:
                    continue
                name = names[family][alias]
                unit = accredited_unit(
                    host=host,
                    systemd_user=systemd_user,
                    family=family,
                    scope=scope,
                    name=name,
                    values=inventories[(host, systemd_user, scope)][name],
                    source_sha256=sources[(family, alias)],
                )
                if unit["activeState"] != "inactive" or unit["unitFileState"] not in {
                    "disabled",
                    "not-found",
                    "",
                }:
                    fail(
                        f"alias {alias} has a writer unit outside its declared host placement"
                    )
    return result


def fleet_leases(
    document: dict[str, Any],
    aliases: dict[str, dict[str, str]],
    *,
    allow_unknown_active: bool = False,
) -> dict[tuple[str, str], bool]:
    if document.get("schemaVersion") != 3:
        fail("fleet snapshot schemaVersion is unsupported")
    rows = array_value(document.get("leases"), "fleet snapshot leases")
    leases: dict[tuple[str, str], bool] = {}
    for raw in rows:
        row = object_value(raw, "fleet snapshot lease")
        if set(row) != {"tenant_id", "alias", "active"}:
            fail("fleet snapshot lease has unexpected fields")
        tenant, alias, active = row["tenant_id"], row["alias"], row["active"]
        if (
            not isinstance(tenant, str)
            or not isinstance(alias, str)
            or not isinstance(active, bool)
        ):
            fail("fleet snapshot lease has invalid values")
        key = (tenant, alias)
        if key in leases:
            fail("fleet snapshot has a duplicate lease")
        leases[key] = active
    declared = {(entry["tenant"], alias) for alias, entry in aliases.items()}
    unknown_active = sorted(
        key for key, active in leases.items() if active and key not in declared
    )
    if unknown_active and not allow_unknown_active:
        fail("fleet snapshot contains an active undeclared writer lease")
    return leases


def build_snapshot(
    ops_root: pathlib.Path,
    fleet: dict[str, Any],
    compose_writers: list[str],
    *,
    legacy_pre_migration: bool = False,
) -> dict[str, Any]:
    manifest_path = ops_root / "container-aliases.json"
    manifest_sha256 = sha256_bytes(manifest_path.read_bytes())
    aliases = manifest_aliases(ops_root)
    if len(compose_writers) != len(set(compose_writers)) or any(
        re.fullmatch(r"[a-z0-9][a-z0-9_-]*", item) is None for item in compose_writers
    ):
        fail("Compose writer inventory is invalid or duplicated")
    leases = fleet_leases(fleet, aliases, allow_unknown_active=legacy_pre_migration)
    if legacy_pre_migration and leases.get(("Steven", "zeus"), False):
        fail("legacy pre-migration writer capture requires Zeus lease offline")
    unit_rows = unit_inventory(ops_root, aliases)
    active_aliases = 0
    for row in unit_rows:
        alias = row["alias"]
        key = (row["tenant"], alias)
        unit_active = any(item["activeState"] == "active" for item in row["units"])
        lease_active = unit_active if legacy_pre_migration else leases.get(key, False)
        if not legacy_pre_migration and lease_active != unit_active:
            fail(f"alias {alias} unit/lease writer state is inconsistent")
        if legacy_pre_migration and alias == "zeus" and unit_active:
            fail("legacy pre-migration writer capture requires Zeus unit offline")
        row["leaseActive"] = lease_active
        active_aliases += int(unit_active)
    if sha256_bytes(manifest_path.read_bytes()) != manifest_sha256:
        fail("canonical alias manifest changed during writer snapshot capture")
    return {
        "aliases": unit_rows,
        "composeWriters": sorted(compose_writers),
        "kind": SNAPSHOT_KIND,
        "manifestSha256": manifest_sha256,
        "schemaVersion": 2,
        "writersExpectedCandidate": active_aliases + len(compose_writers),
    }


def classify_compose_model(
    model: dict[str, Any],
    runtime_image: str,
    console_image: str,
    legacy_compose_images: dict[str, set[str]] | None = None,
) -> list[tuple[str, str, str]]:
    services = object_value(model.get("services"), "Compose services")
    if not services:
        fail("Compose model has no services")
    result: list[tuple[str, str, str]] = []
    for name, raw in sorted(services.items()):
        if name not in COMPOSE_ROLES:
            fail(f"Compose model contains an unclassified materialized service: {name}")
        body = object_value(raw, f"Compose service {name}")
        image = body.get("image")
        if not isinstance(image, str) or not image or "\t" in image or "\n" in image:
            fail(f"Compose service {name} image is invalid")
        role = COMPOSE_ROLES[name]
        if (name == "dispatcher" or role == "writer") and body.get(
            "restart"
        ) != "unless-stopped":
            fail(
                f"Compose database mutator {name} lacks the restart-safe release policy"
            )
        if role in {"migrator", "core", "writer"} and image != runtime_image:
            if role not in {"core", "writer"} or legacy_compose_images is None:
                fail(f"Compose {role} service {name} does not use the selected runtime")
            if image not in legacy_compose_images.get(name, set()):
                fail(
                    f"Compose {role} service {name} image is not authorized by "
                    "the legacy fleet snapshot"
                )
        if role == "console" and image != console_image:
            fail("Compose console does not use the selected console image")
        if role in {"observability", "infrastructure"} and image in {
            runtime_image,
            console_image,
        }:
            fail(f"Compose {role} service {name} aliases a release image")
        if role == "observability":
            environment = body.get("environment", {})
            if isinstance(environment, list):
                environment_keys = {
                    item.split("=", 1)[0]
                    for item in environment
                    if isinstance(item, str)
                }
            else:
                environment_keys = set(object_value(environment, f"{name} environment"))
            if any(
                key == "DATABASE_URL"
                or key == "DATABASE_URL_FILE"
                or key.startswith("PG")
                for key in environment_keys
            ):
                fail(f"observability service {name} has Cauce database authority")
            secrets = body.get("secrets", [])
            for secret in array_value(secrets, f"{name} secrets"):
                if isinstance(secret, str):
                    secret_name = secret
                else:
                    secret_name = object_value(secret, f"{name} secret").get("source")
                if secret_name in {"database_url", "postgres_ca"}:
                    fail(
                        f"observability service {name} mounts Cauce database credentials"
                    )
        result.append((role, name, image))
    for required in ("migrator", "gateway", "dispatcher", "outbox-metrics", "console"):
        if required not in services:
            fail(f"Compose model lacks mandatory service {required}")
    return result


def legacy_fleet_compose_images(
    path: pathlib.Path,
    expected_sha256: str,
    runtime_image: str,
    console_image: str,
) -> dict[str, set[str]]:
    """Return per-service image aliases from one authenticated bootstrap snapshot."""
    if DIGEST_RE.fullmatch(expected_sha256) is None:
        fail("legacy fleet snapshot SHA-256 is invalid")
    content = private_file(path, label="legacy fleet snapshot")
    if sha256_bytes(content) != expected_sha256:
        fail("legacy fleet snapshot differs from its authorized SHA-256")
    document = read_json_bytes(content, "legacy fleet snapshot")
    if (
        set(document) != {"kind", "project", "schemaVersion", "selectors", "services"}
        or document.get("kind") != "cauce-v3-legacy-pre-migration-fleet"
        or document.get("project") != "cauce-v3-prod"
        or document.get("schemaVersion") != 1
    ):
        fail("legacy fleet snapshot envelope is invalid")
    selectors = object_value(document.get("selectors"), "legacy fleet snapshot selectors")
    if set(selectors) != {
        "console", "manifest", "manifestSha256", "normalizedConsole",
        "normalizedRuntime", "runtime",
    }:
        fail("legacy fleet snapshot selectors are invalid")
    if (
        selectors.get("normalizedRuntime") != runtime_image
        or selectors.get("normalizedConsole") != console_image
        or not isinstance(selectors.get("manifest"), str)
        or not pathlib.PurePosixPath(selectors["manifest"]).is_absolute()
        or DIGEST_RE.fullmatch(str(selectors.get("manifestSha256"))) is None
    ):
        fail("legacy fleet snapshot differs from the selected release inputs")
    allowed: dict[str, set[str]] = {}
    seen: set[str] = set()
    services = array_value(document.get("services"), "legacy fleet snapshot services")
    if not services:
        fail("legacy fleet snapshot services are empty")
    for raw in services:
        service = object_value(raw, "legacy fleet snapshot service")
        if set(service) != {
            "configHash", "configImage", "containerId", "exitCode", "imageId",
            "repositoryDigest", "service", "status",
        }:
            fail("legacy fleet snapshot service record is invalid")
        name = service.get("service")
        configured = service.get("configImage")
        repository_digest = service.get("repositoryDigest")
        if (
            not isinstance(name, str)
            or re.fullmatch(r"[a-z0-9][a-z0-9_.-]{0,127}", name) is None
            or name in seen
            or not isinstance(configured, str)
            or not configured
            or any(character.isspace() for character in configured)
            or not isinstance(repository_digest, str)
            or IMAGE_REF_RE.fullmatch(repository_digest) is None
            or not isinstance(service.get("imageId"), str)
            or DIGEST_RE.fullmatch(service["imageId"]) is None
            or not isinstance(service.get("containerId"), str)
            or re.fullmatch(r"[a-f0-9]{12,64}", service["containerId"]) is None
            or not isinstance(service.get("configHash"), str)
            or re.fullmatch(r"[a-f0-9]{64}", service["configHash"]) is None
            or not isinstance(service.get("exitCode"), int)
        ):
            fail("legacy fleet snapshot image/config identity is invalid")
        seen.add(name)
        if name == "migrator":
            if service.get("status") != "exited" or service["exitCode"] != 0:
                fail("legacy fleet snapshot migrator is not exited/0")
        elif service.get("status") != "running" or service["exitCode"] != 0:
            fail("legacy fleet snapshot long-lived service is not running")
        if COMPOSE_ROLES.get(name) in {"core", "writer"}:
            allowed[name] = {configured, repository_digest}
    if "migrator" not in seen:
        fail("legacy fleet snapshot omits the materialized migrator")
    return allowed


def validate_snapshot(
    snapshot: dict[str, Any], ops_root: pathlib.Path | None = None
) -> None:
    if (
        set(snapshot)
        != {
            "aliases",
            "composeWriters",
            "kind",
            "manifestSha256",
            "schemaVersion",
            "writersExpectedCandidate",
        }
        or snapshot.get("kind") != SNAPSHOT_KIND
        or snapshot.get("schemaVersion") != 2
    ):
        fail("writer snapshot top-level contract is invalid")
    manifest_sha = snapshot["manifestSha256"]
    if not isinstance(manifest_sha, str) or DIGEST_RE.fullmatch(manifest_sha) is None:
        fail("writer snapshot manifest digest is invalid")
    if (
        ops_root is not None
        and sha256_bytes((ops_root / "container-aliases.json").read_bytes())
        != manifest_sha
    ):
        fail("writer snapshot differs from the canonical alias manifest")
    compose = array_value(snapshot["composeWriters"], "writer snapshot Compose writers")
    if compose != sorted(set(compose)) or any(
        not isinstance(item, str) or re.fullmatch(r"[a-z0-9][a-z0-9_-]*", item) is None
        for item in compose
    ):
        fail("writer snapshot Compose writer set is invalid")
    aliases = array_value(snapshot["aliases"], "writer snapshot aliases")
    names: set[str] = set()
    expected = len(compose)
    expected_aliases = manifest_aliases(ops_root) if ops_root is not None else None
    observed_order: list[str] = []
    for raw in aliases:
        row = object_value(raw, "writer snapshot alias")
        if set(row) != {
            "alias",
            "host",
            "systemdUser",
            "tenant",
            "leaseActive",
            "units",
        }:
            fail("writer snapshot alias contract is invalid")
        alias = row["alias"]
        if (
            not isinstance(alias, str)
            or re.fullmatch(r"[a-z][a-z0-9-]*", alias) is None
            or alias in names
        ):
            fail("writer snapshot alias identity is invalid or duplicated")
        names.add(alias)
        observed_order.append(alias)
        if (
            not isinstance(row["tenant"], str)
            or not row["tenant"]
            or any(ord(char) < 32 for char in row["tenant"])
            or not isinstance(row["leaseActive"], bool)
        ):
            fail("writer snapshot alias tenant/lease is invalid")
        if (
            not isinstance(row["host"], str)
            or HOST_RE.fullmatch(row["host"]) is None
            or not isinstance(row["systemdUser"], str)
            or USER_RE.fullmatch(row["systemdUser"]) is None
        ):
            fail("writer snapshot alias host/systemd user is invalid")
        if expected_aliases is not None:
            expected_alias = expected_aliases.get(alias)
            if expected_alias is None or any(
                row[field] != expected_alias[field]
                for field in ("host", "systemdUser", "tenant")
            ):
                fail(
                    "writer snapshot alias placement differs from the canonical manifest"
                )
        units = array_value(row["units"], "writer snapshot units")
        if len(units) != 3:
            fail("writer snapshot must contain the exact three canonical unit families")
        active_count = 0
        enabled_count = 0
        active_index: int | None = None
        enabled_index: int | None = None
        expected_units = (
            ("host-native", "system", f"cauce-v3-alias-{alias}.service"),
            ("container-system", "system", f"cauce-v3-container-{alias}.service"),
            ("container-rootless", "user", f"cauce-v3-container-{alias}.service"),
        )
        for index, (
            raw_unit,
            (expected_family, expected_scope, expected_name),
        ) in enumerate(zip(units, expected_units, strict=True)):
            unit = object_value(raw_unit, "writer snapshot unit")
            if set(unit) != {
                "activeState",
                "family",
                "fragmentSha256",
                "loadState",
                "mainPid",
                "name",
                "scope",
                "subState",
                "unitFileState",
            }:
                fail("writer snapshot unit contract is invalid")
            if (
                unit["activeState"] not in ACTIVE_STATES
                or unit["loadState"] not in LOADED_STATES
            ):
                fail("writer snapshot unit state is invalid")
            if (
                unit["unitFileState"] not in ENABLED_STATES
                or type(unit["mainPid"]) is not int
            ):
                fail("writer snapshot unit file/process state is invalid")
            if (
                unit["loadState"] == "loaded"
                and unit["unitFileState"] not in {"enabled", "disabled"}
            ) or (
                unit["loadState"] == "not-found"
                and (
                    unit["unitFileState"] not in {"not-found", ""}
                    or unit["activeState"] != "inactive"
                )
            ):
                fail("writer snapshot unit lacks an exact reversible state")
            if (
                not isinstance(unit["name"], str)
                or UNIT_RE.fullmatch(unit["name"]) is None
            ):
                fail("writer snapshot unit name is invalid")
            if unit["scope"] not in {"system", "user"} or unit["family"] not in {
                "host-native",
                "container-system",
                "container-rootless",
            }:
                fail("writer snapshot unit scope/family is invalid")
            if (
                unit["family"] != expected_family
                or unit["scope"] != expected_scope
                or unit["name"] != expected_name
            ):
                fail("writer snapshot unit is not the exact canonical alias unit")
            fragment_sha = unit["fragmentSha256"]
            if fragment_sha is not None and (
                not isinstance(fragment_sha, str)
                or DIGEST_RE.fullmatch(fragment_sha) is None
            ):
                fail("writer snapshot unit fragment digest is invalid")
            if (unit["loadState"] == "loaded") != (fragment_sha is not None):
                fail("writer snapshot unit load/fragment contract is invalid")
            if unit["mainPid"] < 0 or (unit["activeState"] == "active") != (
                unit["mainPid"] > 0
            ):
                fail("writer snapshot unit process state is invalid")
            if not isinstance(unit["subState"], str) or any(
                ord(char) < 32 for char in unit["subState"]
            ):
                fail("writer snapshot unit substate is invalid")
            active_count += int(unit["activeState"] == "active")
            if unit["activeState"] == "active":
                active_index = index
            if unit["unitFileState"] == "enabled":
                enabled_count += 1
                enabled_index = index
        if (
            active_count > 1
            or enabled_count > 1
            or (active_count == 1 and active_index != enabled_index)
            or bool(active_count) != row["leaseActive"]
        ):
            fail("writer snapshot alias active unit/lease contract is invalid")
        expected += active_count
    if observed_order != sorted(observed_order):
        fail("writer snapshot aliases are not in canonical order")
    if expected_aliases is not None and names != set(expected_aliases):
        fail("writer snapshot omits or adds canonical aliases")
    if (
        type(snapshot["writersExpectedCandidate"]) is not int
        or snapshot["writersExpectedCandidate"] != expected
    ):
        fail("writer snapshot candidate writer count is inconsistent")


def validate_zeus_activation_rotation(
    old_snapshot: dict[str, Any] | None,
    new_snapshot: dict[str, Any],
) -> None:
    """Admit only the bounded inactive -> active Zeus writer-set change.

    The snapshot itself authenticates placement, unit fragments and the
    unit/lease relationship.  This comparison deliberately ignores process IDs
    and substates, but it does not ignore the active unit family: every other
    alias and every Compose writer must retain the same active set.

    ``old_snapshot`` is absent only for an idempotent retry after the new
    selector is already durable.  That path still has to prove Zeus active in
    the selected snapshot and is followed by a live ``restored`` check.
    """

    if new_snapshot["composeWriters"] != (
        old_snapshot["composeWriters"] if old_snapshot is not None else new_snapshot["composeWriters"]
    ):
        fail("writer rotation changes the Compose writer active set")

    new_aliases = {row["alias"]: row for row in new_snapshot["aliases"]}
    new_zeus = new_aliases.get("zeus")
    if new_zeus is None or new_zeus["tenant"] != "Steven":
        fail("writer rotation snapshot does not contain canonical Zeus")
    new_active = [
        unit for unit in new_zeus["units"] if unit["activeState"] == "active"
    ]
    if not new_zeus["leaseActive"] or len(new_active) != 1:
        fail("writer rotation does not prove Zeus active in both unit and lease state")

    if old_snapshot is None:
        return
    if old_snapshot["manifestSha256"] != new_snapshot["manifestSha256"]:
        fail("writer rotation changes the canonical alias manifest")
    old_aliases = {row["alias"]: row for row in old_snapshot["aliases"]}
    if set(old_aliases) != set(new_aliases):
        fail("writer rotation changes the declared alias set")
    old_zeus = old_aliases.get("zeus")
    if old_zeus is None or old_zeus["tenant"] != "Steven":
        fail("selected writer snapshot does not contain canonical Zeus")
    if old_zeus["leaseActive"] or any(
        unit["activeState"] == "active" for unit in old_zeus["units"]
    ):
        fail("selected writer snapshot does not prove Zeus inactive")

    identity_fields = ("alias", "host", "systemdUser", "tenant")
    unit_identity_fields = ("family", "fragmentSha256", "loadState", "name", "scope")
    for alias in sorted(old_aliases):
        old_row = old_aliases[alias]
        new_row = new_aliases[alias]
        if any(old_row[field] != new_row[field] for field in identity_fields):
            fail("writer rotation changes an alias identity or placement")
        if len(old_row["units"]) != len(new_row["units"]):
            fail("writer rotation changes an alias unit set")
        for old_unit, new_unit in zip(old_row["units"], new_row["units"], strict=True):
            if any(
                old_unit[field] != new_unit[field] for field in unit_identity_fields
            ):
                fail("writer rotation changes a declared unit identity")
        if alias == "zeus":
            continue
        if old_row["leaseActive"] != new_row["leaseActive"] or [
            unit["activeState"] for unit in old_row["units"]
        ] != [unit["activeState"] for unit in new_row["units"]]:
            fail("writer rotation includes an active-set drift outside Zeus")

    if (
        new_snapshot["writersExpectedCandidate"]
        != old_snapshot["writersExpectedCandidate"] + 1
    ):
        fail("writer rotation changes the candidate writer count by more than Zeus")


def current_units(
    ops_root: pathlib.Path,
    snapshot: dict[str, Any],
) -> dict[tuple[str, str, str, str], dict[str, Any]]:
    aliases = {
        row["alias"]: {
            "host": row["host"],
            "systemdUser": row["systemdUser"],
            "tenant": row["tenant"],
        }
        for row in snapshot["aliases"]
    }
    observed = unit_inventory(ops_root, aliases, admit_partial_transition=True)
    return {
        (row["host"], row["systemdUser"], unit["scope"], unit["name"]): unit
        for row in observed
        for unit in row["units"]
    }


def assert_snapshot_manifest(ops_root: pathlib.Path, snapshot: dict[str, Any]) -> None:
    try:
        observed = sha256_bytes((ops_root / "container-aliases.json").read_bytes())
    except OSError as error:
        raise WriterStateError("canonical alias manifest is unavailable") from error
    if observed != snapshot["manifestSha256"]:
        fail("writer snapshot differs from the canonical alias manifest")


def assert_unit_state(
    ops_root: pathlib.Path, snapshot: dict[str, Any], mode: str
) -> None:
    assert_snapshot_manifest(ops_root, snapshot)
    observed = current_units(ops_root, snapshot)
    assert_snapshot_manifest(ops_root, snapshot)
    for row in snapshot["aliases"]:
        for expected in row["units"]:
            actual = observed[
                (row["host"], row["systemdUser"], expected["scope"], expected["name"])
            ]
            for field in ("family", "fragmentSha256", "loadState", "name", "scope"):
                if actual[field] != expected[field]:
                    fail("declared writer unit identity changed")
            was_enabled = expected["unitFileState"] == "enabled"
            if mode == "fenced" and was_enabled:
                if actual["unitFileState"] != "disabled":
                    fail("declared external writer unit is not persistently fenced")
            elif actual["unitFileState"] != expected["unitFileState"]:
                fail("declared writer unit enabled state changed")
            if mode == "captured":
                for field in ("activeState", "subState", "mainPid"):
                    if actual[field] != expected[field]:
                        fail("declared writer unit changed after snapshot capture")
            elif mode == "fenced":
                if actual["activeState"] == "active" or actual["mainPid"] != 0:
                    fail("declared external writer unit is still active")
            elif mode == "restored":
                expected_active = expected["activeState"] == "active"
                if (actual["activeState"] == "active") != expected_active:
                    fail("declared writer unit active set was not restored exactly")
                if expected_active != (actual["mainPid"] > 0):
                    fail("restored writer unit process state is invalid")
            else:
                fail("unsupported writer assertion mode")


def assert_unit_transitionable(
    ops_root: pathlib.Path,
    snapshot: dict[str, Any],
    operation: str,
) -> None:
    """Admit an exact retry after a partial or lost systemd response."""
    if operation not in {"fence", "restore"}:
        fail("unsupported writer unit transition")
    assert_snapshot_manifest(ops_root, snapshot)
    observed = current_units(ops_root, snapshot)
    assert_snapshot_manifest(ops_root, snapshot)
    for row in snapshot["aliases"]:
        for expected in row["units"]:
            actual = observed[
                (row["host"], row["systemdUser"], expected["scope"], expected["name"])
            ]
            for field in ("family", "fragmentSha256", "loadState", "name", "scope"):
                if actual[field] != expected[field]:
                    fail("declared writer unit identity changed during transition")
            was_active = expected["activeState"] == "active"
            was_enabled = expected["unitFileState"] == "enabled"
            is_active = actual["activeState"] == "active"
            if is_active and not was_active:
                fail("a writer unit absent from the recovery active set became active")
            if not was_enabled:
                if was_active:
                    fail(
                        "active writer unit is not exactly enabled and cannot be fenced reversibly"
                    )
                if actual["unitFileState"] != expected["unitFileState"]:
                    fail(
                        "an inactive writer unit changed enabled state during transition"
                    )
                continue
            if actual["unitFileState"] not in {"enabled", "disabled"}:
                fail("writer unit has an ambiguous persistent enabled state")


def systemctl_mutate(
    ops_root: pathlib.Path,
    snapshot: dict[str, Any],
    operation: str,
) -> None:
    """Move exact reversible units by phases and re-observe every phase.

    A failed systemctl response is ambiguous: it may precede the mutation, follow
    it, or leave only one of the unit-file/process changes durable. In
    particular, restore must never start a unit whose enablement was not observed
    as restored. Keep progressing independent units, but return failure after
    recording the safest observable state so the locked caller can reconcile or
    retry deterministically.
    """
    if operation not in {"fence", "restore"}:
        fail("unsupported systemd writer mutation")

    reversible = sorted(
        (
            (row, unit)
            for row in snapshot["aliases"]
            for unit in row["units"]
            if unit["unitFileState"] == "enabled"
        ),
        key=lambda item: (item[0]["host"], item[1]["scope"], item[1]["name"]),
    )
    failures: list[str] = []
    incomplete = False

    def observe(row: dict[str, Any], expected: dict[str, Any]) -> dict[str, Any]:
        assert_snapshot_manifest(ops_root, snapshot)
        actual = current_units(ops_root, snapshot)[
            (row["host"], row["systemdUser"], expected["scope"], expected["name"])
        ]
        assert_snapshot_manifest(ops_root, snapshot)
        for field in ("family", "fragmentSha256", "loadState", "name", "scope"):
            if actual[field] != expected[field]:
                fail("declared writer unit identity changed during mutation")
        return actual

    def mutate(row: dict[str, Any], expected: dict[str, Any], *arguments: str) -> None:
        assert_snapshot_manifest(ops_root, snapshot)
        command = systemctl_command(
            row["host"],
            row["systemdUser"],
            expected["scope"],
            [*arguments, expected["name"]],
            mutating=True,
        )
        try:
            run_host_command(
                command,
                label=f"systemd {operation} phase for host {row['host']}",
            )
        except WriterStateError:
            failures.append(f"systemd {operation} phase failed for host {row['host']}")
        assert_snapshot_manifest(ops_root, snapshot)

    for row, expected in reversible:
        actual = observe(row, expected)
        if operation == "fence":
            if (
                actual["unitFileState"] != "disabled"
                or actual["activeState"] == "active"
            ):
                mutate(row, expected, "disable", "--now")
                actual = observe(row, expected)
            if (
                actual["unitFileState"] != "disabled"
                or actual["activeState"] == "active"
            ):
                incomplete = True
            continue

        if actual["unitFileState"] != "enabled":
            mutate(row, expected, "enable")
            actual = observe(row, expected)
        if actual["unitFileState"] != "enabled":
            # Do not turn a persistently fenced unit back into a live writer.
            incomplete = True
            continue
        expected_active = expected["activeState"] == "active"
        if expected_active and actual["activeState"] != "active":
            mutate(row, expected, "start")
            actual = observe(row, expected)
        if (actual["activeState"] == "active") != expected_active:
            incomplete = True

    if failures:
        fail("; ".join(failures))
    if incomplete:
        fail("systemd writer mutation did not reach the required observable state")


def validate_fleet_against_snapshot(
    snapshot: dict[str, Any],
    fleet: dict[str, Any],
    mode: str,
    *,
    legacy_pre_migration: bool = False,
) -> None:
    aliases = {
        row["alias"]: {
            "host": row["host"],
            "systemdUser": row["systemdUser"],
            "tenant": row["tenant"],
        }
        for row in snapshot["aliases"]
    }
    leases = fleet_leases(fleet, aliases, allow_unknown_active=legacy_pre_migration)
    if legacy_pre_migration:
        if mode != "captured":
            fail("legacy pre-migration lease exception is valid only for captured state")
        if leases.get(("Steven", "zeus"), False):
            fail("legacy pre-migration writer check requires Zeus lease offline")
        return
    for row in snapshot["aliases"]:
        observed = leases.get((row["tenant"], row["alias"]), False)
        expected = row["leaseActive"] if mode in {"captured", "restored"} else False
        if observed != expected:
            fail("database writer leases do not match the required release state")


def atomic_marker(
    path: pathlib.Path,
    snapshot_path: pathlib.Path,
    snapshot_sha256: str,
    *,
    release_id: str,
    mode: str,
    writers_expected: int,
    writers_observed: int,
) -> None:
    if path != pathlib.Path(f"{snapshot_path}.state.json"):
        fail(
            "release-state marker path is not derived from the selected writer snapshot"
        )
    if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", release_id) is None:
        fail("release-state marker release ID is invalid")
    if mode not in {"candidate", "rollback_bridge_degraded"}:
        fail("release-state marker mode is invalid")
    if writers_expected < 0 or writers_observed < 0:
        fail("release-state marker writer counts are invalid")
    if mode == "candidate" and writers_expected != writers_observed:
        fail(
            "candidate release-state marker requires expected and observed writers to match"
        )
    if mode == "rollback_bridge_degraded" and (
        writers_expected != 0 or writers_observed != 0
    ):
        fail(
            "rollback bridge release-state marker requires zero expected and observed writers"
        )
    body = {
        "kind": MARKER_KIND,
        "mode": mode,
        "releaseId": release_id,
        "schemaVersion": 1,
        "snapshotPath": os.fspath(snapshot_path),
        "snapshotSha256": snapshot_sha256,
        "updatedAt": dt.datetime.now(dt.timezone.utc)
        .isoformat()
        .replace("+00:00", "Z"),
        "writersExpected": writers_expected,
        "writersObserved": writers_observed,
    }
    content = (json.dumps(body, sort_keys=True, separators=(",", ":")) + "\n").encode()
    parent = path.parent
    if not path.is_absolute() or not parent.is_dir() or parent.is_symlink():
        fail("release-state marker path is unsafe")
    parent_metadata = parent.lstat()
    if (
        parent_metadata.st_uid not in {0, os.geteuid()}
        or stat.S_IMODE(parent_metadata.st_mode) & 0o022
    ):
        fail("release-state marker parent is not owned and protected")
    temporary = parent / f".{path.name}.tmp-{os.getpid()}-{secrets.token_hex(8)}"
    descriptor = -1
    try:
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor = os.open(temporary, flags, 0o600)
        view = memoryview(content)
        while view:
            view = view[os.write(descriptor, view) :]
        os.fchmod(descriptor, 0o444)
        os.fsync(descriptor)
        os.close(descriptor)
        descriptor = -1
        if path.exists() or path.is_symlink():
            private_file(path, label="release-state marker", mode=0o444)
        os.replace(temporary, path)
        directory = os.open(parent, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def check_marker(
    path: pathlib.Path,
    snapshot_path: pathlib.Path,
    snapshot_sha256: str,
    *,
    release_id: str,
    mode: str,
    writers_expected: int,
    writers_observed: int,
) -> None:
    if path != pathlib.Path(f"{snapshot_path}.state.json"):
        fail(
            "release-state marker path is not derived from the selected writer snapshot"
        )
    content = private_file(path, label="release-state marker", mode=0o444)
    try:
        content.decode("ascii")
    except UnicodeDecodeError as error:
        raise WriterStateError(
            "release-state marker must be canonical ASCII"
        ) from error
    marker = read_json_bytes(content, "release-state marker")
    if set(marker) != {
        "kind",
        "mode",
        "releaseId",
        "schemaVersion",
        "snapshotPath",
        "snapshotSha256",
        "updatedAt",
        "writersExpected",
        "writersObserved",
    }:
        fail("release-state marker fields are invalid")
    canonical = (
        json.dumps(marker, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode("ascii")
    if content != canonical:
        fail("release-state marker bytes are not canonical")
    expected = {
        "kind": MARKER_KIND,
        "mode": mode,
        "releaseId": release_id,
        "schemaVersion": 1,
        "snapshotPath": os.fspath(snapshot_path),
        "snapshotSha256": snapshot_sha256,
        "writersExpected": writers_expected,
        "writersObserved": writers_observed,
    }
    if any(marker.get(key) != value for key, value in expected.items()):
        fail("release-state marker does not describe the selected release state")
    timestamp = marker["updatedAt"]
    if not isinstance(timestamp, str) or not timestamp.endswith("Z"):
        fail("release-state marker timestamp is invalid")
    try:
        parsed = dt.datetime.fromisoformat(timestamp.removesuffix("Z") + "+00:00")
    except ValueError as error:
        raise WriterStateError("release-state marker timestamp is invalid") from error
    now = dt.datetime.now(dt.timezone.utc)
    if parsed > now + dt.timedelta(seconds=5):
        fail("release-state marker timestamp is from the future")


def publish_snapshot(
    path: pathlib.Path,
    content: bytes,
    ops_root: pathlib.Path,
    *,
    allow_identical: bool = False,
) -> str:
    snapshot = read_json_bytes(content, "writer snapshot candidate")
    validate_snapshot(snapshot, ops_root)
    canonical = (
        json.dumps(snapshot, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode()
    if content != canonical:
        fail("writer snapshot candidate bytes are not canonical")
    parent = path.parent
    if (
        not path.is_absolute()
        or not path.name
        or path.name in {".", ".."}
        or not parent.is_dir()
        or parent.is_symlink()
    ):
        fail("writer snapshot destination is unsafe")
    parent_metadata = parent.lstat()
    if (
        parent_metadata.st_uid not in {0, os.geteuid()}
        or stat.S_IMODE(parent_metadata.st_mode) & 0o022
    ):
        fail("writer snapshot parent is not owned and protected")
    if path.exists() or path.is_symlink():
        if not allow_identical:
            fail("writer snapshot destination already exists")
        observed = private_file(path, label="published writer snapshot")
        if observed != content:
            fail("existing writer snapshot differs from the retry candidate")
        return sha256_bytes(content)
    temporary = parent / f".{path.name}.tmp-{os.getpid()}-{secrets.token_hex(8)}"
    try:
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor = os.open(temporary, flags, 0o600)
        try:
            view = memoryview(content)
            while view:
                view = view[os.write(descriptor, view) :]
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        os.link(temporary, path, follow_symlinks=False)
        # The hard link is the create-only publication point.  From here on the
        # destination is never unlinked on error: a retry can authenticate
        # identical bytes, while deleting after a failed read-back could race a
        # same-UID rename and remove another process's file.
        os.unlink(temporary)
        directory = os.open(parent, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
        observed = private_file(path, label="published writer snapshot")
        if observed != content:
            fail("published writer snapshot differs after atomic read-back")
        return sha256_bytes(content)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ops-root",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent,
    )
    subparsers = parser.add_subparsers(dest="action", required=True)
    capture = subparsers.add_parser("capture")
    capture.add_argument("--compose-writer", action="append", default=[])
    capture.add_argument("--legacy-pre-migration", action="store_true")
    publish = subparsers.add_parser("publish")
    publish.add_argument("--path", required=True, type=pathlib.Path)
    publish.add_argument("--allow-identical", action="store_true")
    guarded = subparsers.add_parser("guarded-exec")
    guarded.add_argument("command", nargs=argparse.REMAINDER)
    compose_model = subparsers.add_parser("compose-model")
    compose_model.add_argument("--runtime-image", required=True)
    compose_model.add_argument("--console-image", required=True)
    compose_model.add_argument("--legacy-fleet-snapshot", type=pathlib.Path)
    compose_model.add_argument("--legacy-fleet-snapshot-sha256")
    for action in ("validate", "check", "fence", "restore"):
        child = subparsers.add_parser(action)
        child.add_argument("--snapshot", required=True, type=pathlib.Path)
        child.add_argument("--expected-sha256", required=True)
        if action == "check":
            child.add_argument(
                "--mode", choices=("captured", "fenced", "restored"), required=True
            )
            child.add_argument("--fleet-stdin", action="store_true")
            child.add_argument("--compose-writer", action="append", default=[])
            child.add_argument("--legacy-pre-migration", action="store_true")
    marker = subparsers.add_parser("marker")
    marker.add_argument("--snapshot", required=True, type=pathlib.Path)
    marker.add_argument("--expected-sha256", required=True)
    marker.add_argument("--path", required=True, type=pathlib.Path)
    marker.add_argument("--release-id", required=True)
    marker.add_argument(
        "--mode", choices=("candidate", "rollback_bridge_degraded"), required=True
    )
    marker.add_argument("--writers-expected", required=True, type=int)
    marker.add_argument("--writers-observed", required=True, type=int)
    marker_check = subparsers.add_parser("marker-check")
    marker_check.add_argument("--snapshot", required=True, type=pathlib.Path)
    marker_check.add_argument("--expected-sha256", required=True)
    marker_check.add_argument("--path", required=True, type=pathlib.Path)
    marker_check.add_argument("--release-id", required=True)
    marker_check.add_argument(
        "--mode", choices=("candidate", "rollback_bridge_degraded"), required=True
    )
    marker_check.add_argument("--writers-expected", required=True, type=int)
    marker_check.add_argument("--writers-observed", required=True, type=int)
    rotation_check = subparsers.add_parser("rotation-check")
    rotation_check.add_argument("--old-snapshot", type=pathlib.Path)
    rotation_check.add_argument("--old-sha256")
    rotation_check.add_argument("--new-snapshot", required=True, type=pathlib.Path)
    rotation_check.add_argument("--new-sha256", required=True)
    arguments = parser.parse_args(argv)
    lock_descriptor: int | None = None
    try:
        ops_root = arguments.ops_root.resolve(strict=True)
        if arguments.action in MUTATING_ACTIONS:
            lock_descriptor = authenticated_transition_lock()
        if arguments.action == "compose-model":
            model = read_json_bytes(sys.stdin.buffer.read(), "Compose model")
            legacy_images = None
            if (arguments.legacy_fleet_snapshot is None) != (
                arguments.legacy_fleet_snapshot_sha256 is None
            ):
                fail("legacy fleet snapshot path and SHA-256 must be supplied together")
            if arguments.legacy_fleet_snapshot is not None:
                legacy_images = legacy_fleet_compose_images(
                    arguments.legacy_fleet_snapshot,
                    arguments.legacy_fleet_snapshot_sha256,
                    arguments.runtime_image,
                    arguments.console_image,
                )
            for role, name, image in classify_compose_model(
                model, arguments.runtime_image, arguments.console_image, legacy_images
            ):
                print(role, name, image, sep="\t")
            return 0
        if arguments.action == "guarded-exec":
            return guarded_exec(ops_root, arguments.command)
        if arguments.action == "capture":
            fleet = read_json_bytes(sys.stdin.buffer.read(), "fleet snapshot")
            snapshot = build_snapshot(
                ops_root,
                fleet,
                arguments.compose_writer,
                legacy_pre_migration=arguments.legacy_pre_migration,
            )
            print(json.dumps(snapshot, sort_keys=True, separators=(",", ":")))
            return 0
        if arguments.action == "publish":
            print(
                publish_snapshot(
                    arguments.path,
                    sys.stdin.buffer.read(),
                    ops_root,
                    allow_identical=arguments.allow_identical,
                )
            )
            return 0
        if arguments.action == "rotation-check":
            if (arguments.old_snapshot is None) != (arguments.old_sha256 is None):
                fail("writer rotation old snapshot selector is incomplete")
            old_snapshot = (
                load_snapshot(arguments.old_snapshot, arguments.old_sha256, ops_root)
                if arguments.old_snapshot is not None
                and arguments.old_sha256 is not None
                else None
            )
            new_snapshot = load_snapshot(
                arguments.new_snapshot, arguments.new_sha256, ops_root
            )
            authenticated_remote_guard(new_snapshot)
            validate_zeus_activation_rotation(old_snapshot, new_snapshot)
            print("release writer state rotation-check passed")
            return 0
        snapshot = load_snapshot(
            arguments.snapshot, arguments.expected_sha256, ops_root
        )
        if arguments.action == "validate":
            pass
        elif arguments.action == "check":
            if sorted(arguments.compose_writer) != snapshot["composeWriters"]:
                fail(
                    "configured Compose writer set differs from the selected recovery snapshot"
                )
            if arguments.mode in {"fenced", "restored"}:
                authenticated_remote_guard(snapshot)
            assert_unit_state(ops_root, snapshot, arguments.mode)
            if arguments.fleet_stdin:
                fleet = read_json_bytes(sys.stdin.buffer.read(), "fleet snapshot")
                validate_fleet_against_snapshot(
                    snapshot,
                    fleet,
                    arguments.mode,
                    legacy_pre_migration=arguments.legacy_pre_migration,
                )
        elif arguments.action == "fence":
            authenticated_remote_guard(snapshot)
            assert_unit_transitionable(ops_root, snapshot, "fence")
            systemctl_mutate(ops_root, snapshot, "fence")
        elif arguments.action == "restore":
            authenticated_remote_guard(snapshot)
            assert_unit_transitionable(ops_root, snapshot, "restore")
            systemctl_mutate(ops_root, snapshot, "restore")
        elif arguments.action == "marker":
            atomic_marker(
                arguments.path,
                arguments.snapshot,
                arguments.expected_sha256,
                release_id=arguments.release_id,
                mode=arguments.mode,
                writers_expected=arguments.writers_expected,
                writers_observed=arguments.writers_observed,
            )
        elif arguments.action == "marker-check":
            check_marker(
                arguments.path,
                arguments.snapshot,
                arguments.expected_sha256,
                release_id=arguments.release_id,
                mode=arguments.mode,
                writers_expected=arguments.writers_expected,
                writers_observed=arguments.writers_observed,
            )
        print(f"release writer state {arguments.action} passed")
        return 0
    except (OSError, subprocess.CalledProcessError, WriterStateError) as error:
        print(f"release writer state failed: {error}", file=sys.stderr)
        return 1
    finally:
        if lock_descriptor is not None:
            os.close(lock_descriptor)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
