"""Flat surface of the PTY agent: `import cauce_pty_agent as agent` reaches every name."""
from __future__ import annotations

import os
import sys
import time
import types

from .agent import (
    BACKOFF_MAX,
    BACKOFF_MIN,
    SELECT_CEILING,
    PtyAgent,
    assert_not_root,
    main,
)
from .framing import (
    AGENT_PROTOCOL_VERSION,
    ARGUMENT_EXIT,
    CLOCK_SKEW,
    DATA_TAGS,
    IDENTITY_RE,
    MAX_DATA,
    MAX_FRAME,
    MODES,
    PERMANENT_EXIT,
    PREFIXED_TAGS,
    SESSION_ID_BYTES,
    SESSION_ID_RE,
    TAG_AGENT_HELLO,
    TAG_CLOSE,
    TAG_CLOSED,
    TAG_GEOMETRY,
    TAG_HELLO_ACK,
    TAG_INPUT_REFUSED,
    TAG_OPEN,
    TAG_OPEN_ERR,
    TAG_OPEN_OK,
    TAG_PAUSE_OUTPUT,
    TAG_PING,
    TAG_PONG,
    TAG_READ,
    TAG_READ_DATA,
    TAG_READ_DONE,
    TAG_READ_ERR,
    TAG_READ_OK,
    TAG_RESIZE,
    TAG_RESUME_OUTPUT,
    TAG_STDIN,
    TAG_STDOUT,
    TAG_TERMINAL_RESPONSE,
    TAG_WRITE,
    TAG_WRITE_BATCH,
    TAG_WRITE_BATCH_CANCEL,
    TAG_WRITE_BATCH_DATA,
    TAG_WRITE_BATCH_ERR,
    TAG_WRITE_BATCH_OK,
    TAG_WRITE_CANCEL,
    TAG_WRITE_DATA,
    TAG_WRITE_ERR,
    TAG_WRITE_OK,
    TICKET_RE,
    FrameDecoder,
    PermanentError,
    ProtocolError,
    TicketError,
    authorize_ticket,
    b64url_decode,
    decode_data,
    encode_data,
    encode_frame,
    encode_json,
    fail,
    log,
    verify_ticket,
)
from .governance_paths import (
    DIR_SCAN_CAP,
    FEATURES,
    MAX_DIR_DEPTH,
    MAX_DIR_ENTRIES,
    MAX_DOCUMENT_BYTES,
    MAX_READ_PATH,
    MAX_WRITE_BATCH_BYTES,
    MAX_WRITE_BATCH_FILES,
    MAX_WRITE_TRANSACTIONS,
    NEVER_SERVE_BASENAMES,
    NEVER_SERVE_SUFFIXES,
    PROJECT_DOC_FALLBACK_LIMIT,
    PROJECT_DOC_MAX_BYTES_LIMIT,
    READ_INDEX_BUDGET,
    READ_KINDS,
    SHA256_RE,
    UNSAFE_TEXT_CODE_POINT_RANGES,
    GovernancePathsMixin,
    ReadPathTypeError,
    ReadSymlinkError,
    _has_unsafe_text_code_point,
    _valid_project_doc_fallback,
)
from .governance_read import (
    GovernanceReadMixin,
)
from .governance_write import (
    GovernanceBatchEntry,
    GovernanceWrite,
    GovernanceWriteBatch,
    GovernanceWriteMixin,
)
from .runtime_facts import (
    BUNDLE_KEYS,
    RUNTIME_FACT_KEYS,
    RUNTIME_PATH_FACT_KEYS,
    _command,
    _command_list,
    _runtime_facts_config,
    load_bundle,
    validate_bundle,
)
from .session import (
    DYNAMIC_CAPABILITY_CHECK_INTERVAL,
    FLUSH_BYTES,
    FLUSH_INTERVAL,
    HELLO_TIMEOUT,
    KILL_GRACE,
    MAX_COLS,
    MAX_ROWS,
    MAX_SESSIONS,
    MAX_TERMINAL_RESPONSE_BYTES,
    MIN_COLS,
    MIN_ROWS,
    OUTBOUND_HIGH_WATER,
    PING_TIMEOUT,
    READ_ONLY_MODES,
    SESSION_HIGH_WATER,
    SESSION_INPUT_HIGH_WATER,
    TERMINAL_CURSOR_RESPONSE_RE,
    TERMINAL_FIXED_RESPONSES,
    TOMBSTONE_SECONDS,
    PtySession,
    SessionMixin,
    _cloexec,
    _window,
    is_terminal_emulator_response,
    set_window_size,
)
from .tmux import (
    MAX_SESSION_STORE_BYTES,
    OPENCLAW_NATIVE_SESSION_RE,
    TMUX_IDENTITY_RE,
    TMUX_SOCKET_RE,
    TMUX_TUI_WINDOW,
    _openclaw_tui_config,
    _tmux_tui_config,
    resolve_openclaw_tui_command,
    resolve_tmux_tui_command,
)

__all__ = [
    "os",
    "time",
    "AGENT_PROTOCOL_VERSION",
    "ARGUMENT_EXIT",
    "BACKOFF_MAX",
    "BACKOFF_MIN",
    "BUNDLE_KEYS",
    "CLOCK_SKEW",
    "DATA_TAGS",
    "DIR_SCAN_CAP",
    "DYNAMIC_CAPABILITY_CHECK_INTERVAL",
    "FEATURES",
    "FLUSH_BYTES",
    "FLUSH_INTERVAL",
    "FrameDecoder",
    "GovernanceBatchEntry",
    "GovernancePathsMixin",
    "GovernanceReadMixin",
    "GovernanceWrite",
    "GovernanceWriteBatch",
    "GovernanceWriteMixin",
    "HELLO_TIMEOUT",
    "IDENTITY_RE",
    "KILL_GRACE",
    "MAX_COLS",
    "MAX_DATA",
    "MAX_DIR_DEPTH",
    "MAX_DIR_ENTRIES",
    "MAX_DOCUMENT_BYTES",
    "MAX_FRAME",
    "MAX_READ_PATH",
    "MAX_ROWS",
    "MAX_SESSIONS",
    "MAX_SESSION_STORE_BYTES",
    "MAX_TERMINAL_RESPONSE_BYTES",
    "MAX_WRITE_BATCH_BYTES",
    "MAX_WRITE_BATCH_FILES",
    "MAX_WRITE_TRANSACTIONS",
    "MIN_COLS",
    "MIN_ROWS",
    "MODES",
    "NEVER_SERVE_BASENAMES",
    "NEVER_SERVE_SUFFIXES",
    "OPENCLAW_NATIVE_SESSION_RE",
    "OUTBOUND_HIGH_WATER",
    "PERMANENT_EXIT",
    "PING_TIMEOUT",
    "PREFIXED_TAGS",
    "PROJECT_DOC_FALLBACK_LIMIT",
    "PROJECT_DOC_MAX_BYTES_LIMIT",
    "PermanentError",
    "ProtocolError",
    "PtyAgent",
    "PtySession",
    "READ_INDEX_BUDGET",
    "READ_KINDS",
    "READ_ONLY_MODES",
    "RUNTIME_FACT_KEYS",
    "RUNTIME_PATH_FACT_KEYS",
    "ReadPathTypeError",
    "ReadSymlinkError",
    "SELECT_CEILING",
    "SESSION_HIGH_WATER",
    "SESSION_ID_BYTES",
    "SESSION_ID_RE",
    "SESSION_INPUT_HIGH_WATER",
    "SHA256_RE",
    "SessionMixin",
    "TAG_AGENT_HELLO",
    "TAG_CLOSE",
    "TAG_CLOSED",
    "TAG_GEOMETRY",
    "TAG_HELLO_ACK",
    "TAG_INPUT_REFUSED",
    "TAG_OPEN",
    "TAG_OPEN_ERR",
    "TAG_OPEN_OK",
    "TAG_PAUSE_OUTPUT",
    "TAG_PING",
    "TAG_PONG",
    "TAG_READ",
    "TAG_READ_DATA",
    "TAG_READ_DONE",
    "TAG_READ_ERR",
    "TAG_READ_OK",
    "TAG_RESIZE",
    "TAG_RESUME_OUTPUT",
    "TAG_STDIN",
    "TAG_STDOUT",
    "TAG_TERMINAL_RESPONSE",
    "TAG_WRITE",
    "TAG_WRITE_BATCH",
    "TAG_WRITE_BATCH_CANCEL",
    "TAG_WRITE_BATCH_DATA",
    "TAG_WRITE_BATCH_ERR",
    "TAG_WRITE_BATCH_OK",
    "TAG_WRITE_CANCEL",
    "TAG_WRITE_DATA",
    "TAG_WRITE_ERR",
    "TAG_WRITE_OK",
    "TERMINAL_CURSOR_RESPONSE_RE",
    "TERMINAL_FIXED_RESPONSES",
    "TICKET_RE",
    "TMUX_IDENTITY_RE",
    "TMUX_SOCKET_RE",
    "TMUX_TUI_WINDOW",
    "TOMBSTONE_SECONDS",
    "TicketError",
    "UNSAFE_TEXT_CODE_POINT_RANGES",
    "_cloexec",
    "_command",
    "_command_list",
    "_has_unsafe_text_code_point",
    "_openclaw_tui_config",
    "_runtime_facts_config",
    "_tmux_tui_config",
    "_valid_project_doc_fallback",
    "_window",
    "assert_not_root",
    "authorize_ticket",
    "b64url_decode",
    "decode_data",
    "encode_data",
    "encode_frame",
    "encode_json",
    "fail",
    "is_terminal_emulator_response",
    "load_bundle",
    "log",
    "main",
    "resolve_openclaw_tui_command",
    "resolve_tmux_tui_command",
    "set_window_size",
    "validate_bundle",
    "verify_ticket",
]

_MODULES = tuple(
    module for name, module in list(sys.modules.items())
    if name.startswith(__name__ + ".")
)


class _FlatSurface(types.ModuleType):
    """Rebinding a name on the package reaches the module that reads it.

    The suite addresses this package as the single module the code used to be, and patches
    values on it (`mock.patch.object(agent, "DIR_SCAN_CAP", 3)`). The reader now holds its own
    binding, so the write is forwarded to it; without this a patched limit would leave the
    real code running the unpatched value and the test would pass over nothing.
    """

    def __setattr__(self, name: str, value: object) -> None:
        super().__setattr__(name, value)
        for module in _MODULES:
            if name in vars(module):
                setattr(module, name, value)


sys.modules[__name__].__class__ = _FlatSurface
