import { WebSocket, type RawData } from 'ws';
import { ClaimedAckSchema, isRfcUuid, type Tenant, type WsOutbound } from '@cauce/protocol';
import { StoreError, type ConnectionSessionFence } from '@cauce/store';
import type { DeliveryClaimRecord, GatewayAck } from '../../app.js';
import type { Session, SessionClaim } from './contracts.js';

const MAX_RECENT_SESSION_CLAIMS = 1_024;
/**
 * Cap on claims that are rehydrated on connect. Well above any reasonable quota: it's only
 * there so a pathological queue doesn't drag thousands of rows into the socket. If the alias
 * had more live claims than this, the budget is already zero anyway.
 */
export const MAX_REHYDRATED_CLAIMS = 256;
export const MAX_DRAIN_ROUNDS = 16;
// ACK states that return the delivery to the terminal or retryable world and therefore remove
// it from agents.max_concurrent_deliveries. It is the complementary set of ('leased','accepted',
// 'started'), which is exactly what claimDeliveries counts.
export const RELEASES_CAPACITY: ReadonlySet<string> = new Set(['done', 'failed', 'dead', 'retry']);

export function sessionKey(tenantId: Tenant, alias: string): string {
  return `${tenantId}:${alias}`;
}

export function connectionToken(value: unknown): string {
  if (!isRfcUuid(value)) {
    throw new StoreError('fenced', 'connection token is required');
  }
  return value;
}

export function parseConnectionBoundBody<T extends Record<string, unknown>>(
  body: unknown,
  parse: (value: unknown) => T,
): T & { connection_token: string } {
  if (body === null || typeof body !== 'object' || Array.isArray(body)) {
    throw new StoreError('invalid_input', 'connection-bound request must be an object');
  }
  const { connection_token: rawToken, ...withoutToken } = body as Record<string, unknown>;
  return { ...parse(withoutToken), connection_token: connectionToken(rawToken) };
}

export function sessionFence(session: Session): ConnectionSessionFence {
  return {
    tenant_id: session.tenantId,
    alias: session.alias,
    instance_id: session.instanceId,
    epoch: session.epoch,
    connection_token: session.connectionToken,
  };
}

export function isSocketOpen(socket: WebSocket): boolean {
  return socket.readyState === WebSocket.OPEN;
}

// With `unknown` no outgoing frame was tied to the wire union: a stale literal, or a field the
// adapter's `.strict()` parser rejects, only failed where a test looked. `WsOutbound` tells `tsc`.
export function send(socket: WebSocket, message: WsOutbound): boolean {
  if (!isSocketOpen(socket)) return false;
  try {
    socket.send(JSON.stringify(message));
    return true;
  } catch {
    return false;
  }
}

export function rawDataText(data: RawData): string {
  if (Buffer.isBuffer(data)) return data.toString('utf8');
  if (Array.isArray(data)) return Buffer.concat(data).toString('utf8');
  return Buffer.from(data).toString('utf8');
}

export function claimFromDelivery(delivery: DeliveryClaimRecord, fallbackDeadlineMs: number): SessionClaim {
  if (typeof delivery.event_id !== 'string' || delivery.event_id.length === 0 ||
      typeof delivery.claim_token !== 'string' || delivery.claim_token.length === 0 ||
      !Number.isInteger(delivery.attempt) || delivery.attempt < 1) {
    throw new Error('repository returned an incomplete delivery claim');
  }
  // `ack_deadline_at` was generated by PostgreSQL; it is the single source of truth on when the
  // reaper can take the claim. If it comes illegible, the configured deadline is used, which is
  // the same thing the store just applied.
  const deadlineMs = Date.parse(delivery.ack_deadline_at);
  return {
    attempt: delivery.attempt,
    claim_token: delivery.claim_token,
    admissionExpiresAtMs: Number.isFinite(deadlineMs) ? deadlineMs : Date.now() + fallbackDeadlineMs
  };
}

export function normalizeDeliveryClaim(delivery: DeliveryClaimRecord, fallbackDeadlineMs: number): DeliveryClaimRecord {
  claimFromDelivery(delivery, fallbackDeadlineMs);
  return delivery;
}

export function parseAck(value: unknown): GatewayAck {
  return ClaimedAckSchema.parse(value);
}

export function assertAckClaim(ack: GatewayAck, expected?: Pick<SessionClaim, 'attempt' | 'claim_token'>): void {
  if (expected && (ack.attempt !== expected.attempt || ack.claim_token !== expected.claim_token)) {
    throw new StoreError('fenced', 'ACK claim does not match the delivered event');
  }
}

export function rememberRecentClaim(session: Session, deliveryId: string, claim: SessionClaim): void {
  session.recentClaims.delete(deliveryId);
  session.recentClaims.set(deliveryId, claim);
  while (session.recentClaims.size > MAX_RECENT_SESSION_CLAIMS) {
    const oldest = session.recentClaims.keys().next().value;
    if (oldest === undefined) break;
    session.recentClaims.delete(oldest);
  }
}

/**
 * Removes from `claims` the claims whose deadline has already passed. This is
 * not an optimization: an expired claim can never be renewed (`ackDelivery` requires
 * `ack_deadline_at > now()`, same condition), so if it stayed in the map it would occupy a slot
 * forever and the agent would run out of work until reconnecting. It is moved to `recentClaims`
 * instead of deleted, because deleting it would make a late ACK not correlate and a legacy client
 * would eat a 'fenced' with socket close, when today it receives `ownership_lost` and stays alive.
 *
 * The budget is not computed here: the database subtracts it under the durable alias lock.
 * This map only preserves ACK correlation and schedules the next drain by expiration.
 */
export function pruneExpiredClaims(session: Session, nowMs: number): void {
  for (const [deliveryId, claim] of [...session.claims]) {
    if (claim.admissionExpiresAtMs <= nowMs) {
      session.claims.delete(deliveryId);
      rememberRecentClaim(session, deliveryId, claim);
    }
  }
}
